java_thrift_library(
    sources = ["dummy.thrift"],
    compiler = "scrooge",
    compiler_args = ["--finagle"],
    language = "android",
    tags = ["nolint"],
    dependencies = ["3rdparty:thrift-0.6.1"],
)
