page(
  name='3rdparty',
  source='3rdparty.md',
  links=[
    'examples/src/java/org/pantsbuild/example:3rdparty_jvm',
    'examples/src/python/example:3rdparty_py',
  ],
)

page(
  name='announce_201409',
  source='announce_201409.md',
)

page(
  name='build_files',
  source='build_files.md',
  links=[
    ':first_tutorial',
  ]
)

page(
  name='first_concepts',
  source='first_concepts.md',
  links=[
    ':first_tutorial',
  ]
)

page(
  name='first_tutorial',
  source='first_tutorial.md',
  links=[
    ':first_concepts',
    ':invoking',
    'examples/src/java/org/pantsbuild/example:readme',
    'examples/src/python/example:readme',
  ]
)

page(
  name='index',
  source='index.md',
  links=[
    ':3rdparty',
    ':announce_201409',
    ':build_files',
    ':first_concepts',
    ':first_tutorial',
    ':install',
    ':invoking',
    ':powered_by',
    ':publish',
    ':setup_repo',
    ':target_addresses',
    ':tshoot',
    ':with_emacs',
    ':with_intellij',
    'examples/src/java/org/pantsbuild/example:page',
    'examples/src/java/org/pantsbuild/example:readme',
    'examples/src/python/example:readme',
    'examples/src/thrift/org/pantsbuild/example:readme',
    'src/python/pants/docs:readme',
    ])

page(
  name='invoking',
  source='invoking.md',
  links=[
    ':first_tutorial',
    ':target_addresses',
  ]
)

page(
  name='install',
  source='install.md',
  links=[
    ':setup_repo',
  ]
)

page(
  name='powered_by',
  source='powered_by.md',
)

page(
  name='publish',
  source='publish.md',
  links=[
    ':3rdparty',
  ]
)

page(
  name='setup_repo',
  source='setup_repo.md',
  links=[
    ':build_files',
    ':first_concepts',
    ':publish',
    'src/python/pants/docs:dev_tasks',
    'src/python/pants/docs:dev_tasks_publish_extras',
    'src/python/pants/docs:howto_contribute',
    'src/python/pants/docs:howto_plugin',
  ]
)

page(
  name='target_addresses',
  source='target_addresses.md'
)

page(
  name='tshoot',
  source='tshoot.md',
  links=[
    'src/python/pants/docs:howto_ask',
  ]
)

page(
  name='with_emacs',
  source='with_emacs.md'
)

page(
  name='with_intellij',
  source='with_intellij.md',
  links=[
    'src/python/pants/docs:intellij',
  ],
)
