# Copyright 2025 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    overrides={"rules.py": dict(dependencies=["./scripts"])},
)

python_tests(
    name="tests",
)
