# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'stats',
  sources = globs('*.py'),
  dependencies = [
    'src/python/pants/subsystem',
    'src/python/pants/util:dirutil',
  ],
)
