# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    '3rdparty/python:future',
    'src/python/pants/subsystem',
    'src/python/pants/util:dirutil',
  ]
)
