java_library(name='cycle1',
             dependencies=[
               '3rdparty:guava',
               'testprojects/src/java/com/pants/testproject/cycle2',
             ],
             sources = ['Foo.java'],
)
