python_library(
  dependencies = [
    '3rdparty/python:future',
    '3rdparty/python:pex',
    'src/python/pants/backend/python:plugin',
    'src/python/pants/backend/python/subsystems',
    'src/python/pants/backend/python/targets',
    'src/python/pants/base:workunit',
    'src/python/pants/base:build_environment',
    'src/python/pants/base:exceptions',
    'src/python/pants/build_graph',
    'src/python/pants/subsystem',
    'src/python/pants/util:contextutil',
    'src/python/pants/task',
  ],
)