# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(name='reader',
  dependencies=[
    'src/resources/com/pants/example/jaxb',
  ],
  sources=['VegetableReader.java'],
)