python_library(
  name = 'testutils',
  sources = globs('*.py'),
  dependencies = [
    pants('src/python/twitter/pants/base:parse_context'),
    pants('src/python/twitter/pants/base:target'),
    pants('src/python/twitter/pants/reporting'),
    pants('src/python/twitter/pants/targets:common'),
  ],
)
