# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_sources(resolve="jar_tool_dev")

resources(name="src", sources=["*.java"])
