# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='test_basic_invocation_conversion_rules',
  sources=['test_basic_invocation_conversion_rules.py'],
  dependencies=[
    'contrib/rust/src/python/pants/contrib/rust/utils:basic_invocation_conversion_rules',
  ]
)

python_tests(
  name='test_basic_invocation_conversion_utils',
  sources=['test_basic_invocation_conversion_utils.py'],
  dependencies=[
    'contrib/rust/src/python/pants/contrib/rust/utils:basic_invocation_conversion_utils',
  ]
)

python_tests(
  name='test_custom_build_invocation_conversion_rules',
  sources=['test_custom_build_invocation_conversion_rules.py'],
  dependencies=[
    'contrib/rust/src/python/pants/contrib/rust/utils:custom_build_invocation_conversion_rules',
  ]
)

python_tests(
  name='test_custom_build_output_parsing',
  sources=['test_custom_build_output_parsing.py'],
  dependencies=[
    'contrib/rust/src/python/pants/contrib/rust/utils:custom_build_output_parsing',
  ]
)


