java_library(
    name = "fatal",
    sources = ["Warning.java"],
    fatal_warnings = True,
)

java_library(
    name = "nonfatal",
    sources = ["Warning.java"],
    fatal_warnings = False,
)

java_library(
    name = "defaultfatal",
    sources = ["Warning.java"],
)
