java_library(
  name='fatal',
  sources=['Warning.java'],
  extra_compile_options=['fatal_warnings'],
)

java_library(
  name='nonfatal',
  sources=['Warning.java'],
  extra_compile_options=['-fatal_warnings'],
)

java_library(
  name='defaultfatal',
  sources=['Warning.java'],
)
