# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(name='missingdirectdepswhitelist2',
  sources=rglobs('*.java'),
  dependencies=['testprojects/src/java/com/pants/testproject/publish/hello/greet']
)
