# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(name = 'resourcejar',
  dependencies = [
    '3rdparty:guava',
    '3rdparty:junit',
  ],

  sources = [
    'ResourceJar.java',
  ],

  resources = [
    'testprojects/tests/resources/org/pantsbuild/testproject/resourcejar',
  ],
)