# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
    dependencies=[
        'contrib/thrifty/tests/thrift/org/pantsbuild/contrib/thrifty/client',
        'contrib/thrifty/tests/thrift/org/pantsbuild/contrib/thrifty/common',
    ],
)
