# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'src/python/pants/backend/native/targets',
    'src/python/pants/engine/internals:native',
  ],
  tags = {"partially_type_checked"},
)
