#This is a dummy build file for Intellij Plugin integration test.
#Please do not remove this BUILD file

target(
  dependencies = [
   'examples/src/scala/org/pantsbuild/example/hello/exe:exe',
  ]
)
