java_library(
  provides=artifact(
    org='org.pantsbuild',
    name='junit-runner-security-manager-public',
    repo=public,
    publication_metadata=pants_library("""
      Exceptions for use with org.pantsbuild#junit-runner that support using the integrated security manager.
    """)
  ),
  platform='java7',
)
