# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  name='plugins',
  dependencies = [
    'src/python/internal_backend/sitegen:plugin',
    'src/python/internal_backend/repositories:plugin',
  ]
)
