# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_protobuf_library(
  sources=['*.proto'],
  provides=artifact(
    org='org.pantsbuild.testproject.protobuf',
    name='distance',
    repo=testing,
  )
)
