# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name='cp-directories_directory',
  sources=rglobs('cp-directories/*'),
)

files(
  name='exports_directory',
  sources=rglobs('exports/*'),
)

files(
  name='non_exports_directory',
  sources=rglobs('non_exports/*'),
)
