# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'src/python/pants/auth',
    'src/python/pants/util:contextutil',
    'tests/python/pants_test:test_base',
  ]
)
