# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    ':reporting_resources',
  ],
)

resources(
  name='reporting_resources',
  sources=['assets/**/*', 'templates/**/*.mustache'],
)
