# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

contrib_plugin(
  name='plugin',
  dependencies=[
    'contrib/bloop/src/python/pants/contrib/bloop/tasks',
  ],
  distribution_name='pantsbuild.pants.contrib.bloop',
  description='Bloop support for pants.',
  register_goals=True,
)
