# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Example of thrift with python keywords

python_thrift_library(name='keywords-python',
  sources=['keywords.thrift'],
)
