# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_grpcio_library(
  sources=['imports.proto'],
  dependencies=[
    'examples/3rdparty/python:protobuf',
    'examples/src/protobuf/org/pantsbuild/example/grpcio/service'
  ]
)
