{
  "allow_builds": true,
  "allow_prereleases": false,
  "allow_wheels": true,
  "build_isolation": true,
  "constraints": [],
  "elide_unused_requires_dist": false,
  "excluded": [],
  "locked_resolves": [
    {
      "locked_requirements": [
        {
          "artifacts": [
            {
              "algorithm": "sha256",
              "hash": "b95102bd82e6f67c836186b51c13114aa586a20e8cb6441bde24d4070542009d",
              "url": "https://files.pythonhosted.org/packages/0b/35/2cb27f4a0a68bacde1bdbc2cd4ba8d0d5be95fca04010c7bd83caa96cd20/dockerfile-3.4.0-cp39-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl"
            },
            {
              "algorithm": "sha256",
              "hash": "a4549d4f038483c25906d4fec56bb6ffe82ae26e0f80a15f2c0fedbb50712053",
              "url": "https://files.pythonhosted.org/packages/8e/bf/246a02d803318131d809b13d285244e4047def667df906ad123e7d8405b2/dockerfile-3.4.0-cp39-abi3-macosx_14_0_arm64.whl"
            },
            {
              "algorithm": "sha256",
              "hash": "ed33446a76007cbb3f28c247f189cc06db34667d4f59a398a5c44912d7c13f36",
              "url": "https://files.pythonhosted.org/packages/a1/2a/553b099124685f00c4cc06cda6496db02e43ca51d7b7b5dc68814c6b48be/dockerfile-3.4.0-cp39-abi3-macosx_13_0_x86_64.whl"
            },
            {
              "algorithm": "sha256",
              "hash": "238bb950985c55a525daef8bbfe994a0230aa0978c419f4caa4d9ce0a37343f1",
              "url": "https://files.pythonhosted.org/packages/de/c9/2cdd6060f8f476c41a1638a9e1b28923fb0d9c075dffc41b13137199e207/dockerfile-3.4.0.tar.gz"
            }
          ],
          "project_name": "dockerfile",
          "requires_dists": [],
          "requires_python": ">=3.9",
          "version": "3.4.0"
        }
      ],
      "marker": null,
      "platform_tag": null
    }
  ],
  "only_builds": [],
  "only_wheels": [],
  "overridden": [],
  "path_mappings": {},
  "pex_version": "2.66.0",
  "pip_version": "25.3",
  "prefer_older_binary": false,
  "requirements": [
    "dockerfile<4,>=3.2.0"
  ],
  "requires_python": [
    "CPython<3.14,>=3.9"
  ],
  "resolver_version": "pip-2020-resolver",
  "style": "universal",
  "target_systems": [
    "linux",
    "mac"
  ],
  "transitive": true,
  "use_pep517": null,
  "use_system_time": false
}
