# Copyright 2025 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).
typescript_sources(name="ts_sources")
tsx_sources(name="tsx_sources")
