# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name='bundleresources_directory',
  sources=['bundleresources/**/*'],
)

files(
  name='cucumber_directory',
  sources=['cucumber/**/*'],
)

files(
  name='ideacodeandresources_directory',
  sources=['ideacodeandresources/**/*'],
)

files(
  name='idearesourcesonly_directory',
  sources=['idearesourcesonly/**/*'],
)

files(
  name='ivyclassifier_directory',
  sources=['ivyclassifier/**/*'],
)
