# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name='cucumber_directory',
  sources=rglobs('cucumber/*'),
)

files(
  name='ivyclassifier_directory',
  sources=rglobs('ivyclassifier/*'),
)
