python_library(
  name = 'targets',
  sources = [
    'scala_js_binary.py',
    'scala_js_library.py',
  ],
  dependencies = [
    'src/python/pants/backend/jvm/targets:jvm',
    'src/python/pants/backend/jvm/targets:scala',
    'src/python/pants/backend/jvm/subsystems:scala_js_platform',
    'src/python/pants/base:target',
  ],
)
