# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'targets',
  dependencies = [
    'contrib/scalajs/src/python/pants/contrib/scalajs/subsystems',
    'src/python/pants/backend/jvm/targets:jvm',
    'src/python/pants/backend/jvm/targets:scala',
    'src/python/pants/base:target',
  ],
  sources = globs('*.py'),
)
