# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

source_root('scrooge/src/python', page, python_binary, python_library, resources)
source_root('scrooge/tests/python', page, python_binary, python_library, python_tests, resources)
source_root('scrooge/tests/thrift', page, java_thrift_library)

source_root('spindle/src/python', page, python_binary, python_library, resources)
source_root('spindle/tests/jvm', page, scala_library)
source_root('spindle/3rdparty', jar_library)

source_root('buildgen/src/python', page, python_binary, python_library, resources)
source_root('buildgen/tests/python', python_tests)

source_root('cpp/src/python', python_library)
source_root('cpp/tests/python', python_library, python_tests)
