# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  name = 'plugins',
  dependencies = [
  ]
)

files(
  name = 'isort_cfg',
  sources = ['.isort.cfg'],
)
