# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'src/python/pants/backend/codegen/thrift/python',
    'src/python/pants/backend/python/targets:python',
    'tests/python/pants_test/tasks:task_test_base',
  ]
)
