# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  name='plugins',
  dependencies = [
    'pants-plugins/src/python/internal_backend/rules_for_testing:plugin',
    'pants-plugins/src/python/internal_backend/utilities',
  ],
)
