# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'test_concurrent_overrides_pantsd',
  sources = ['test_concurrent_overrides_pantsd.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_daemon_auto_shutdown_after_first_run',
  sources = ['test_daemon_auto_shutdown_after_first_run.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_dependencies_swap',
  sources = ['test_dependencies_swap.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_inner_runs_dont_deadlock',
  sources = ['test_inner_runs_dont_deadlock.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_aligned_output',
  sources = ['test_pantsd_aligned_output.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_broken_pipe',
  sources = ['test_pantsd_broken_pipe.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_client_env_var_is_inherited_by_pantsd_runner_children',
  sources = ['test_pantsd_client_env_var_is_inherited_by_pantsd_runner_children.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_compile',
  sources = ['test_pantsd_compile.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_environment_scrubbing',
  sources = ['test_pantsd_environment_scrubbing.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_invalidation_file_tracking',
  sources = ['test_pantsd_invalidation_file_tracking.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_invalidation_pants_ini_file',
  sources = ['test_pantsd_invalidation_pants_ini_file.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_invalidation_stale_sources',
  sources = ['test_pantsd_invalidation_stale_sources.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_launch_env_var_is_not_inherited_by_pantsd_runner_children',
  sources = ['test_pantsd_launch_env_var_is_not_inherited_by_pantsd_runner_children.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_lifecycle_invalidation',
  sources = ['test_pantsd_lifecycle_invalidation.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_lifecycle_non_invalidation',
  sources = ['test_pantsd_lifecycle_non_invalidation.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_lifecycle_non_invalidation_on_config_string',
  sources = ['test_pantsd_lifecycle_non_invalidation_on_config_string.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_memory_usage',
  sources = ['test_pantsd_memory_usage.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_pantsd_runner_doesnt_die_after_failed_run',
  sources = ['test_pantsd_pantsd_runner_doesnt_die_after_failed_run.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_pid_change',
  sources = ['test_pantsd_pid_change.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_pid_deleted',
  sources = ['test_pantsd_pid_deleted.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_stacktrace_dump',
  sources = ['test_pantsd_stacktrace_dump.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_stray_runners',
  sources = ['test_pantsd_stray_runners.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_touching_a_file_does_not_restart_daemon',
  sources = ['test_pantsd_touching_a_file_does_not_restart_daemon.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_pantsd_unicode_environment',
  sources = ['test_pantsd_unicode_environment.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_sigint_kills_request_waiting_for_lock',
  sources = ['test_sigint_kills_request_waiting_for_lock.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)

python_tests(
  name = 'test_unhandled_exceptions_only_log_exceptions_once',
  sources = ['test_unhandled_exceptions_only_log_exceptions_once.py'],
  dependencies = [
    'tests/python/pants_test/pantsd:pantsd_integration_test_base',
    'examples/src/java/org/pantsbuild/example:hello_directory',
    'examples/src/python/example:hello_directory',
    'examples/src/scala/org/pantsbuild/example:hello_directory',
    'testprojects/src/java/org/pantsbuild/testproject:bundle_directory',
    'testprojects/src/python:bad_requirements_directory',
    'testprojects/src/python:coordinated_runs_directory',
    'testprojects/src/python:nested_runs_directory',
    'testprojects/src/python:print_env_directory',
  ],
  tags = {'integration', 'partially_type_checked'},
  timeout = 450
)
