# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'plugin',
  dependencies = [
    'pants-plugins/src/python/internal_backend/sitegen/tasks',
    'src/python/pants/goal:task_registrar',
  ],
  tags = {"partially_type_checked"},
)
