junit_tests(name='tests',
  sources=['AllTests.java'],
  dependencies=['3rdparty:junit'],
)

junit_tests(name='exit-after',
  sources=['ExitInAfter.java'],
  dependencies=['3rdparty:junit'],
)

junit_tests(name='exit-before',
  sources=['ExitInBefore.java'],
  dependencies=['3rdparty:junit'],
)

junit_tests(name='exit-before-class',
  sources=['ExitInBeforeClass.java'],
  dependencies=['3rdparty:junit'],
)

junit_tests(name='exit-test-thread',
  sources=['ExitInThreadStartedInTest.java'],
  dependencies=['3rdparty:junit'],
)
