# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
  dependencies=[
    '3rdparty/jvm/org/scala-sbt:io',
    '3rdparty:scalatest',
    'src/scala/org/pantsbuild/zinc/compiler',
  ],
  strict_deps=True,
  platform='java8',
)
