# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_tests(
  name='junit',
  dependencies=[
    '3rdparty:junit',
    '3rdparty/jvm/commons-io',
    'src/java/org/pantsbuild/junit/annotations',
    'src/java/org/pantsbuild/tools/junit',
  ],
  sources=globs('*.java')
)
