# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  name='junit',
  dependencies=[
    'tests/java/org/pantsbuild/tools/junit/impl:junit',
  ]
)

target(
  name='junit-console-runner',
  dependencies=[
    'tests/java/org/pantsbuild/tools/junit/runner:junit-console-runner',
  ]
)
