# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'aliases_directory',
  sources = rglobs('aliases/*'),
)

files(
  name = 'phrases_directory',
  sources = rglobs('phrases/*'),
)

files(
  name = 'printversion_directory',
  sources = rglobs('printversion/*'),
)
