# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

page(name="readme",
     source="README.md",
     dependencies=['examples/src/java/com/pants/examples/hello/main:readme']
)
