# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'pants-plugins/src/python/internal_backend/utilities:plugin',
    'src/python/pants/base:revision',
  ],
)
