# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

scala_library(
  name='scala-test-dep',
  dependencies=[
    '3rdparty:scalatest',
    'tests/java/org/pantsbuild/tools/junit/lib:test-dep',
  ],
  sources=globs('*.scala')
)
