# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jax_ws_library(name='hello-service',
  sources = [
    'HelloService.wsdl',
  ],
  dependencies = [],
)
