#!/usr/bin/env bash
# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

# shellcheck source=build-support/common.sh
source "${REPO_ROOT}/build-support/common.sh"

if ! command -v rustup &> /dev/null; then
  die "Please install Rustup 1.23.0+ and ensure \`rustup\` is on your PATH. See https://rustup.rs."
fi

# This will download some tools needed to build Rust, like Cmake, and will add them to the PATH.
# shellcheck source=build-support/bin/rust/download_build_binaries.sh
source "${REPO_ROOT}/build-support/bin/rust/download_build_binaries.sh"

cd "${REPO_ROOT}/src/rust/engine" || exit "${PIPESTATUS[0]}"
exec cargo "$@"
