#!/usr/bin/env bash
# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

cd "${REPO_ROOT}/src/rust/engine" || exit "${PIPESTATUS[0]}"
exec "${REPO_ROOT}/build-support/bin/native/cargo.sh" "$@"
