#!/usr/bin/env bash
# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

# shellcheck source=build-support/common.sh
source "${REPO_ROOT}/build-support/common.sh"

PY="$(determine_python)"
export PY
export PYTHON_SYS_EXECUTABLE="${PY}" # Consumed by the cpython crate.

if ! command -v rustup &> /dev/null; then
  die "Please install Rustup and ensure \`rustup\` is on your PATH (usually by adding ~/.cargo/bin). See https://rustup.rs."
fi

cd "${REPO_ROOT}/src/rust/engine" || exit "${PIPESTATUS[0]}"
exec cargo "$@"
