#!/usr/bin/env bash
# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)

source ${HERE}/build-support/pants_venv

PANTS_EXE=${HERE}/src/python/pants/bin/pants_exe.py
PANTS_BINARY=src/python/pants/bin:pants
PANTS_PEX="${HERE}/pants.pex"

function run_pants_bare() {
  activate_pants_venv
  PYTHONPATH=${HERE}/src/python python ${PANTS_EXE} "$@"
}

function exec_pants_bare() {
  activate_pants_venv
  PYTHONPATH=${HERE}/src/python exec python ${PANTS_EXE} "$@"
}

if [ ! -z "${PANTS_DEV}" ]; then
  log "*** Running pants in dev mode from ${PANTS_EXE} ***"
  exec_pants_bare "$@"
else
  if [ ! -e "${PANTS_PEX}" ]; then
    log "Building pants.pex to ${PANTS_PEX}..."
    # TODO(John sirois): Re-plumb build such that it grabs constraints from the built python_binary
    # target(s).
    rm -rf ${PANTS_PEX} && \
    run_pants_bare build -v -i "CPython>=2.6,<3" -i "CPython>=3.3" ${PANTS_BINARY} && \
    mv -v ${HERE}/dist/pants.pex ${PANTS_PEX} && \
    chmod +x ${PANTS_PEX}
  fi
  exec "${PANTS_PEX}" "$@"
fi
