#!/usr/bin/env bash
# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# This bootstrap script invokes Pants using a Python 3 interpreter.

# Defaults to allowing either Python 3.6 or 3.7, and allows the user to further constrain to a specific version
# by passing `-6` or `-7`.

# Check for -6 and -7 flags.
if [[ "$1" == "-6" ]]; then
  python_three_six=true
  shift
elif [[ "$1" == "-7" ]]; then
  python_three_seven=true
  shift
fi

# Determine Py3 version
if [ "${python_three_six}" = true ]; then
  export PANTS_USE_PYTHON36=true
  py_version_number="3.6"
elif [ "${python_three_seven}" = true ]; then
  export PANTS_USE_PYTHON37=true
  py_version_number="3.7"
else
  export PANTS_USE_PYTHON3_UNCONSTRAINED=true
  # This only sets a lower bounds on acceptable Python 3 interpreters.
  # The actual interpreter and venv to be used will be set by `pants_venv` and `virtualenv`.
  py_version_number="3.6"
fi

# Use Py3 for subprocesses
export PANTS_PYTHON_SETUP_INTERPRETER_CONSTRAINTS="['CPython>=${py_version_number},<4']"

./pants "$@"
