#!/usr/bin/env bash
# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# This bootstrap script invokes Pants using a Python 3 interpreter.

export PANTS_USE_PYTHON3=true
./pants $@
unset PANTS_USE_PYTHON3
