#!/usr/bin/env bash

# Convenient shortcut script for creating a new Pants rbt review:
#
# ./rbt-create <name> ... <name> <other flags>
#
# will create a review with the specified names as reviewers, with pants-reviews as a group,
# and with the other flags passed through to rbt.

NAME_REGEX="^[a-zA-Z][a-zA-Z_.-]+$"
REVIEWERS=""

while [[ $1 ]] && [[ $1 =~ ${NAME_REGEX} ]]; do
  REVIEWERS="${REVIEWERS},$1"
  shift
done

REVIEWERS=${REVIEWERS:1}  # Strip leading comma.

if [[ ${REVIEWERS} ]]; then
  REVIEWERS_FLAG="--target-people=${REVIEWERS}"
fi

./rbt post -o -g ${REVIEWERS_FLAG} "$@"
