#!/usr/bin/env bash
# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

echo "The ./v2 script is going away soon. Just use ./pants !"

./pants "$@"
