# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'src/python/pants/backend/python/targets',
    'src/python/pants/python',
    'src/python/pants/util:collections',
    'src/python/pants/testutil:test_base',
  ],
  tags = {"partially_type_checked"},
)
