# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'src/python/pants/backend/python/targets',
    'src/python/pants/backend/python:python_requirement',
    'src/python/pants/util:collections',
    'tests/python/pants_test:test_base',
  ]
)
