#!/usr/bin/env bash

readonly REPO_ROOT=$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd -P)
source ${REPO_ROOT}/build-support/common.sh

readonly NATIVE_ROOT="${REPO_ROOT}/src/rust/engine"
readonly MODE=debug
readonly MODE_FLAG=

# TODO(John Sirois): Eliminate this replication of BinaryUtil logic internal to pants code when
# https://github.com/pantsbuild/pants/issues/4006 is complete.
readonly KERNEL=$(uname -s | tr '[:upper:]' '[:lower:]')
case "${KERNEL}" in
  linux)
    readonly EXTENSION=so
    readonly OS_ID=linux/$(uname -m)
    ;;
  darwin)
    readonly EXTENSION=dylib
    readonly OS_ID=mac/$(sw_vers -productVersion | cut -d: -f2 | tr -d ' \t' | cut -d. -f1-2)
    ;;
  *)
    die "Unknown kernel ${KERNEL}, cannot bootstrap pants native code!"
    ;;
esac

readonly CACHE_ROOT=${XDG_CACHE_HOME:-$HOME/.cache}/pants
readonly CACHE_TARGET_DIR=${CACHE_ROOT}/dylib/native-engine/${OS_ID}

function calculate_current_hash() {
  find ${NATIVE_ROOT} -type f | git hash-object -t blob --stdin-paths | fingerprint_data
}

function ensure_prerequisites() {
  # The machine may have a non-rustup rust install and we'll respect that, but in case we need to
  # bootstrap via rustup, we pre-emptively add it to the end of the PATH to avoid the user needing
  # to re-exec their SHELL or otherwise have their PATH permanently altered by the rustup script.
  export PATH="$PATH:$HOME/.cargo/bin"
  if [[ -z "$(which cargo 2>/dev/null || true)" ]]
  then
    log "A rust installation could not be found, installing via the instructions at" \
        "https://www.rustup.rs ..."
    local readonly rustup=$(mktemp -t pants.rustup.XXXXX)
    curl https://sh.rustup.rs -sSf > ${rustup}
    sh ${rustup} -y --no-modify-path 1>&2
    rm -f ${rustup}
    # A soft attempt to control the toolchain - if the user came in with their own cargo on that
    # PATH we'll never get here.
    rustup override set stable 1>&2
  fi
}

function bootstrap_native_code() {
  # Bootstraps the native code and sets NATIVE_BOOTSTRAP_HASH to the resulting hash version.
  ensure_prerequisites
  export NATIVE_BOOTSTRAP_HASH="$(calculate_current_hash)"

  local target_hash_dir="${CACHE_TARGET_DIR}/${NATIVE_BOOTSTRAP_HASH}"
  local target_binary="${target_hash_dir}/native-engine"
  if [ ! -f "${target_binary}" ]
  then
    cargo build --manifest-path ${NATIVE_ROOT}/Cargo.toml ${MODE_FLAG} || exit 1
    mkdir -p ${target_hash_dir}
    cp ${NATIVE_ROOT}/target/${MODE}/libengine.${EXTENSION} ${target_binary}
  fi
}
