#!/usr/bin/env bash
# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

REPO_ROOT=$(cd $(dirname "${BASH_SOURCE[0]}") && cd "$(git rev-parse --show-toplevel)" && pwd)

source ${REPO_ROOT}/build-support/set_archflags.sh

REQUIREMENTS=(
  ${REPO_ROOT}/3rdparty/python/requirements.txt
  ${REPO_ROOT}/3rdparty/python/internal_backend/requirements.txt
  ${REPO_ROOT}/3rdparty/python/twitter/commons/requirements.txt
)

# TODO(John Sirois): Kill this when we switch over to publishing from internal_backend
DEV_REQUIREMENTS=(
  ${REPO_ROOT}/3rdparty/python/dev_only_requirements.txt
)

function log() {
  echo -e "$@" 1>&2
}

function die() {
  (($# > 0)) && log "$@"
  exit 1
}

function venv_dir() {
  if [ ! -z "${PANTS_DEV}" ]; then
    echo ${REPO_ROOT}/build-support/pants_dev_deps.venv
  else
    echo ${REPO_ROOT}/build-support/pants_deps.venv
  fi
}

function fingerprint_data() {
  openssl md5 | cut -d' ' -f2
}

function activate_venv() {
  source "$(venv_dir)/bin/activate"
}

function create_venv() {
  rm -rf "$(venv_dir)"
  "${REPO_ROOT}/build-support/virtualenv" "$(venv_dir)"
}

function activate_pants_venv() {
  if [ ! -z "${PANTS_DEV}" ]; then
    REQUIREMENTS=(
      ${DEV_REQUIREMENTS[@]}
      ${REQUIREMENTS[@]}
    )
  fi

  fingerprint=""
  for req in ${REQUIREMENTS[@]}; do
    fingerprint="${fingerprint}$(cat ${req} | fingerprint_data)"
  done
  fingerprint=$(echo "${fingerprint}" | fingerprint_data)

  BOOTSTRAPPED_FILE="$(venv_dir)/BOOTSTRAPPED.${fingerprint}"

  if ! [ -f ${BOOTSTRAPPED_FILE} ]; then
    log "Bootstrapping pants_deps with requirements:"
    if [ ! -z "${PANTS_DEV}" ]; then
      # Install as an egg so IDEs can grok all deps. Installing as sources may
      # run afoul of this bug: http://youtrack.jetbrains.com/issue/PY-6477.
      # TODO: Remove the --egg once this is resolved. It won't work in the wheel world anyway.
      pip_extra="--egg"
    else
      pip_extra=""
    fi

    for req in ${REQUIREMENTS[@]}; do
      log "  ${req}"
    done

    create_venv
    activate_venv
    for req in ${REQUIREMENTS[@]}; do
      pip install ${pip_extra} -r "${req}" || die "Failed to install requirements from ${req}."
    done
    touch "${BOOTSTRAPPED_FILE}"
  else
    activate_venv
  fi
}

