#!/usr/bin/env bash
# Wrapper for self-bootstrapping virtualenv

set -e

VIRTUALENV_VERSION=15.2.0
VIRTUALENV_PACKAGE_LOCATION=${VIRTUALENV_PACKAGE_LOCATION:-https://pypi.io/packages/source/v/virtualenv}

REPO_ROOT=$(cd $(dirname "${BASH_SOURCE[0]}") && git rev-parse --show-toplevel)
source ${REPO_ROOT}/build-support/common.sh

function determine_python_bin_name() {
  if [ "${PANTS_USE_PYTHON3_UNCONSTRAINED}" = true ]; then
    py_version="3"
  elif [ "${PANTS_USE_PYTHON36}" = true ]; then
    py_version="3.6"
  elif [ "${PANTS_USE_PYTHON37}" = true ]; then
    py_version="3.7"
  else
    py_version="2.7"
  fi
  echo "python${py_version}"
}

if [[ -z "${PY}" ]]; then
  python_bin_name="$(determine_python_bin_name)"
  if which "${python_bin_name}" >/dev/null; then
    PY=`which ${python_bin_name}`
  else
    die "No ${python_bin_name} interpreter found on the path. Python will not work!"
  fi
fi

log "Using python at ${PY}"

HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
if ! [ -f "${HERE}/virtualenv.dist/BOOTSTRAPPED-${VIRTUALENV_VERSION}" ]; then
  pushd "${HERE}" >/dev/null
    VIRTUALENV_PACKAGE_FULL_URL="${VIRTUALENV_PACKAGE_LOCATION}/virtualenv-${VIRTUALENV_VERSION}.tar.gz"
    log "Downloading ${VIRTUALENV_PACKAGE_FULL_URL}..."
    curl -#L -O ${VIRTUALENV_PACKAGE_FULL_URL} || \
      die "Failed to download ${VIRTUALENV_PACKAGE_FULL_URL}."
    rm -rf virtualenv-${VIRTUALENV_VERSION} && \
    tar zxf virtualenv-${VIRTUALENV_VERSION}.tar.gz || \
      die "Failed to extract ${VIRTUALENV_PACKAGE_FULL_URL}."
    # TODO(ksweeney): Checksum
    touch virtualenv-${VIRTUALENV_VERSION}/BOOTSTRAPPED-${VIRTUALENV_VERSION} && \
      rm -rf virtualenv.dist && \
      mv -f virtualenv-${VIRTUALENV_VERSION} virtualenv.dist
  popd >/dev/null
fi

exec "${PY}" "${HERE}/virtualenv.dist/virtualenv.py" "$@"
