#!/usr/bin/env bash
# Wrapper for self-bootstrapping virtualenv
set -e
VIRTUALENV_VERSION=12.1.1
VIRTUALENV_PACKAGE_LOCATION=${VIRTUALENV_PACKAGE_LOCATION:-https://pypi.python.org/packages/source/v/virtualenv}

REPO_ROOT=$(cd $(dirname "${BASH_SOURCE[0]}") && cd "$(git rev-parse --show-toplevel)" && pwd)
source ${REPO_ROOT}/build-support/common.sh


if [[ -z "${PY}" ]]; then
  if which python2.7 >/dev/null; then
    PY=`which python2.7`
  else
    die 'No python2.7 interpreter found on the path.  Python will not work!'
  fi
fi

log "Using ${PY}"

HERE=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
if ! [ -f "${HERE}/virtualenv.dist/BOOTSTRAPPED-${VIRTUALENV_VERSION}" ]; then
  pushd "${HERE}"
  VIRTUALENV_PACKAGE_FULL_URL=${VIRTUALENV_PACKAGE_LOCATION}/virtualenv-${VIRTUALENV_VERSION}.tar.gz
  log "Downloading ${VIRTUALENV_PACKAGE_FULL_URL}..."
  curl -O ${VIRTUALENV_PACKAGE_FULL_URL} || \
    die "Failed to download ${VIRTUALENV_PACKAGE_FULL_URL}."
  rm -rf virtualenv-${VIRTUALENV_VERSION} && \
  tar zxvf virtualenv-${VIRTUALENV_VERSION}.tar.gz || \
    die "Failed to extract ${VIRTUALENV_PACKAGE_FULL_URL}."
  # TODO(ksweeney): Checksum
  touch virtualenv-${VIRTUALENV_VERSION}/BOOTSTRAPPED-${VIRTUALENV_VERSION} && \
    rm -rf virtualenv.dist && \
    mv -v virtualenv-${VIRTUALENV_VERSION} virtualenv.dist
  popd
fi

exec "${PY}" "${HERE}/virtualenv.dist/virtualenv.py" "$@"
