# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='thrift_defaults',
  dependencies=[
    'src/python/pants/backend/codegen/thrift/java',
  ],
)
