#!/usr/bin/env bash
# Script to generate a platform-specific native-image of the pantsbuild zinc wrapper which works to
# compile macros, from a pants project.

# Works on OSX and Linux -- see the README.md in this directory for more usage info.

# TODO: This will be made automatic in pants via https://github.com/pantsbuild/pants/pull/6893.

set -euxo pipefail

# TODO: Right now, NATIVE_IMAGE_EXTRA_ARGS='-H:IncludeResourceBundles=org.scalactic.ScalacticBundle'
# is necessary to build any zinc native-image which compiles any code using scalatest. This
# information should be inferred by the native-image agent, but isn't yet.

# TODO: build off of a more recent graal sha (more recent ones fail to build scalac and more): see
# https://github.com/oracle/graal/issues/1448, as well as #7955!

# ARGUMENTS

# $@: Forwarded to a `./pants compile` invocation which runs with reflection tracing enabled.
# $NATIVE_IMAGE_EXTRA_ARGS: Forwarded to a `native-image` invocation.

# CONSTANTS

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

# shellcheck source=build-support/native-image/build-zinc-native-image.bash
source "${SCRIPT_DIR}/build-zinc-native-image.bash"

GENERATED_CONFIG_DIRNAME="${GENERATED_CONFIG_DIRNAME:-generated-reflect-config}"
GENERATED_CONFIG_DIR="$(normalize_path "$GENERATED_CONFIG_DIRNAME")"
GENERATED_CONFIG_JSON_FILE="${GENERATED_CONFIG_DIR}/reflect-config.json"
GENERATED_BUILD_FILE="${GENERATED_CONFIG_DIR}/BUILD"

# NB: Using $REPO_ROOT as calculated in other scripts in this repo seems to make this script fail
# when run from outside the pants repo!
DOWNLOAD_BINARY_SCRIPT="$(normalize_path "${SCRIPT_DIR}/../bin/download_binary.sh")"

# FUNCTIONS

function download_buildozer {
  "$DOWNLOAD_BINARY_SCRIPT" \
    'buildozer' \
    '0.6.0-80c7f0d45d7e40fa1f7362852697d4a03df557b3'
}

function build_agent_dylib {
  pushd "$(get_substratevm_dir)" >&2
  if is_osx; then
    desired_agent_dylib_path="$(pwd)/libnative-image-agent.dylib"
  else
    desired_agent_dylib_path="$(pwd)/libnative-image-agent.so"
  fi
  if [[ ! -f "$desired_agent_dylib_path" ]]; then
    mx build >&2 || return "$?"
    mx native-image --tool:native-image-agent --verbose >&2 || return "$?"
    if is_osx; then
      cp -v {,lib}native-image-agent.dylib || return "$?"
    else
      cp -v {,lib}native-image-agent.so || return "$?"
    fi >&2 || return "$?"
  fi
  echo "$desired_agent_dylib_path"
  popd >&2
}

# run with tracing on

function run_zinc_compile_with_tracing {
  agent_lib_path="$(build_agent_dylib)"
  if [[ ! -f "$GENERATED_CONFIG_JSON_FILE" ]]; then
    rm -rfv "$GENERATED_CONFIG_DIR"
    mkdir -v "$GENERATED_CONFIG_DIR"
    # TODO: jvm options are ignored from the command line, this is a bug and should be fixed.
    export PANTS_COMPILE_ZINC_JVM_OPTIONS="+['-agentpath:${agent_lib_path}=config-merge-dir=${GENERATED_CONFIG_DIR}']"
    # NB: --worker-count=1 is because the `config-merge-dir` option to the native-image agent will
    # clobber symbols from concurrent compiles.
    ./pants -ldebug \
            --no-zinc-native-image \
            compile.zinc \
            --execution-strategy=hermetic \
            --worker-count=1 \
            --no-incremental \
            --no-use-classpath-jars \
            --cache-ignore \
            "$@"
    unset PANTS_COMPILE_ZINC_JVM_OPTIONS
  fi >&2
  normalize_path "$GENERATED_CONFIG_DIR"
}

# analyze tracing -- trim reflection down to just macros, then find those macros' targets with
# classmap

function trim_reflection_config_to_just_macros {
  # Scala macros are the only entries in reflect-config.json that appear to matter for the purposes
  # of compilation, so we filter down to only those.
  # TODO: do compiler plugins look different?
  jq '[.[] | select(.fields[]? | .name == "MODULE$")]' \
     <"$GENERATED_CONFIG_JSON_FILE" \
     >.tmp-reflect-config \
    && mv -v \
          .tmp-reflect-config \
          "$GENERATED_CONFIG_JSON_FILE"
}

function extract_macro_target_names_from_pants {
  ./pants classmap "$@" >.tmp-classmap || return "$?"

  # Get the class names of all the macro usages, then filter down the above `./pants classmap` to
  # find the targets which provide those classes.
  jq -r '.[] | .name' <"$GENERATED_CONFIG_JSON_FILE" | while read -r class_name; do
    grep -F "$class_name" .tmp-classmap \
      | sed -Ee 's#^.* (.*)$#\1#g'
  done | sort -u
}

# create a BUILD file of the appropriate dependencies

function template_BUILD_file {
  # The 'sed' output substitution within this heredoc will convert a list of pants target specs into
  # double-quoted entries in the 'dependencies' kwarg. It will also prepend '//' to each target
  # address so buildozer recognizes them.
  cat <<EOF
# This file was generated by the scripts in https://github.com/pantsbuild/pants/tree/master/build-support/native-image/.
# DO NOT EDIT!!!

jvm_binary(
  name='generated-native-image-binary',
  main='org.pantsbuild.zinc.compiler.Main',
  dependencies=[
    $(sed -Ee 's#^(.*)$#"//\1",#g')
  ],
)
EOF
}

# generate the deps jar and reflect config at known locations!!!

function chunk_and_normalize_pants_deps_for_buildozer {
  # Buildozer can only run one process in parallel, so we want to add as many dependencies into a
  # single invocation as possible (hence -L200). This function will read pants targets from stdin
  # and output long lines which are converted into a buildozer 'add dependencies' command.
  xargs -t -P1 -L200 printf "//%s " \
    && echo
}

function add_buildozer_macro_deps {
  local buildozer="$(download_buildozer)"
  # Ensure the buildozer download succeeds!
  rc="$?"; [[ "$rc" -ne 0 ]] && return "$rc"
  chunk_and_normalize_pants_deps_for_buildozer | while read -r buildozer_deps_flattened; do
    "$buildozer" "add dependencies ${buildozer_deps_flattened}" \
                 "//${GENERATED_CONFIG_DIRNAME}:generated-native-image-binary"
    rc="$?"; [[ "$rc" -eq 0 || "$rc" -eq 3 ]] || return "$rc"
  done
}

function generate_template_macro_deps_target {
  template_BUILD_file >"$GENERATED_BUILD_FILE"
}

function add_macro_deps_to_generated_target {
  if [[ -f "$GENERATED_BUILD_FILE" ]]; then
    # If the generated BUILD file exists already, pull down buildozer to idempotently add the new
    # deps!
    add_buildozer_macro_deps
  else
    # Otherwise, generate a BUILD file next to the generated native-image json config.
    generate_template_macro_deps_target
  fi
}

function generate_macro_deps_jar {
  # NB: This "gracefully" handles the case of having no macros to add by having pants succeed
  # without outputting any jar. This is passed to the native-image build classpath, which accepts
  # entries that don't exist.
  (extract_macro_target_names_from_pants "$@" \
     | add_macro_deps_to_generated_target \
     && ./pants -ldebug binary "//${GENERATED_CONFIG_DIRNAME}:generated-native-image-binary") \
    >&2 \
    && normalize_path dist/generated-native-image-binary.jar
}

# actually build the zinc image!!!

### EXECUTING!
# NB: It's not clear whether it's possible to set the locale in some ubuntu containers, so we
# simply ignore it here.
export PANTS_IGNORE_UNRECOGNIZED_ENCODING=1
export PY="$(which python3)"

bootstrap_environment >&2

ensure_has_executable \
  'jq' \
  "jq must be installed to be able to manipulate the native-image json config." \
  "Please see https://stedolan.github.io/jq/!" \
  >&2

export JAVA_HOME="$(extract_openjdk_jvmci)"
PATH="$(clone_mx):${PATH}"

readonly ZINC_GENERATED_CONFIG_DIR="$(run_zinc_compile_with_tracing "$@")"
with_pushd "$ZINC_GENERATED_CONFIG_DIR" \
           trim_reflection_config_to_just_macros
readonly MACRO_DEPS_JAR="$(generate_macro_deps_jar "$@")"

create_zinc_image \
  -H:ConfigurationFileDirectories="$GENERATED_CONFIG_DIR" \
  -cp "$MACRO_DEPS_JAR" \
  ${NATIVE_IMAGE_EXTRA_ARGS:-} \
  | while read -r image_location; do
  "$image_location" --help
  echo
done

# NB: if the native-image build fails, and you see the following in the output:
#
#     Caused by: java.lang.VerifyError: class scala.tools.nsc.Global overrides final method isDeveloper.()Z
#
# Please re-run the script at most two more times. This can occur nondeterministically for some
# reason right now.
