#!/usr/bin/env bash
# Script to generate a platform-specific native-image of the pantsbuild zinc wrapper which works to
# compile macros, from a pants project.

# Requires `jq` and `go`. `jq` can be downloaded from https://stedolan.github.io/jq/!
# Works on OSX and Linux -- see the README.md in this directory for more usage info.

# TODO: This will be made automatic in pants via https://github.com/pantsbuild/pants/pull/6893.

set -euxo pipefail

# TODO: Right now, NATIVE_IMAGE_EXTRA_ARGS='-H:IncludeResourceBundles=org.scalactic.ScalacticBundle'
# is necessary to build any zinc native-image which compiles any code using scalatest. This
# information should be inferred by the native-image agent, but isn't yet.

# TODO: build off of a more recent graal sha (more recent ones fail to build scalac and more): see
# https://github.com/oracle/graal/issues/1448, as well as #7955!

# ARGUMENTS

# $@: Forwarded to a `./pants compile` invocation which runs with reflection tracing enabled.
# $NATIVE_IMAGE_EXTRA_ARGS: Forwarded to a `native-image` invocation.

# CONSTANTS

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

# shellcheck source=build-support/native-image/build-zinc-native-image.bash
source "${SCRIPT_DIR}/build-zinc-native-image.bash"

GENERATED_CONFIG_DIR="$(normalize_path "${GENERATED_CONFIG_DIR:-generated-reflect-config}")"
GENERATED_CONFIG_JSON_FILE="${GENERATED_CONFIG_DIR}/reflect-config.json"
GENERATED_BUILD_FILE="${GENERATED_CONFIG_DIR}/BUILD"

# FUNCTIONS

function download_buildozer {
  >&2 go get github.com/bazelbuild/buildtools/buildozer || return "$?"
  which buildozer
}

function build_agent_dylib {
  pushd "$(get_substratevm_dir)" >&2
  if is_osx; then
    desired_agent_dylib_path="$(pwd)/libnative-image-agent.dylib"
  else
    desired_agent_dylib_path="$(pwd)/libnative-image-agent.so"
  fi
  if [[ ! -f "$desired_agent_dylib_path" ]]; then
    mx build >&2 || return "$?"
    mx native-image --tool:native-image-agent --verbose >&2 || return "$?"
    if is_osx; then
      cp -v {,lib}native-image-agent.dylib || return "$?"
    else
      cp -v {,lib}native-image-agent.so || return "$?"
    fi >&2 || return "$?"
  fi
  echo "$desired_agent_dylib_path"
  popd >&2
}

# run with tracing on

function run_zinc_compile_with_tracing {
  agent_lib_path="$(build_agent_dylib)"
  if [[ ! -f "$GENERATED_CONFIG_JSON_FILE" ]]; then
    rm -rfv "$GENERATED_CONFIG_DIR"
    mkdir -v "$GENERATED_CONFIG_DIR"
    # TODO: jvm options are ignored from the command line, this is a bug and should be fixed.
    export PANTS_COMPILE_ZINC_JVM_OPTIONS="+['-agentpath:${agent_lib_path}=config-merge-dir=${GENERATED_CONFIG_DIR}']"
    # NB: --worker-count=1 is because the `config-merge-dir` option to the native-image agent will
    # clobber symbols from concurrent compiles.
    ./pants -ldebug \
            --no-zinc-native-image \
            compile.zinc \
            --execution-strategy=hermetic \
            --worker-count=1 \
            --no-incremental \
            --no-use-classpath-jars \
            --cache-ignore \
            "$@"
    unset PANTS_COMPILE_ZINC_JVM_OPTIONS
  fi >&2
  normalize_path "$GENERATED_CONFIG_DIR"
}

# analyze tracing -- trim reflection down to just macros, then find those macros' targets with
# classmap

function trim_reflection_config_to_just_macros {
  # Scala macros are the only entries in reflect-config.json that appear to matter for the purposes
  # of compilation, so we filter down to only those.
  # TODO: do compiler plugins look different?
  jq '[.[] | select(.fields[]? | .name == "MODULE$")]' \
     <"$GENERATED_CONFIG_JSON_FILE" \
     >.tmp-reflect-config \
    && mv -v \
          .tmp-reflect-config \
          "$GENERATED_CONFIG_JSON_FILE"
}

function extract_macro_target_names_from_pants {
  ./pants classmap "$@" >.tmp-classmap || return "$?"

  # Get the class names of all the macro usages, then filter down the above `./pants classmap` to
  # find the targets which provide those classes.
  jq -r '.[] | .name' <"$GENERATED_CONFIG_JSON_FILE" | while read -r class_name; do
    grep -F "$class_name" .tmp-classmap \
      | sed -Ee 's#^.* (.*)$#\1#g'
  done | sort -u
}

# create a BUILD file of the appropriate dependencies

function template_BUILD_file {
  cat <<EOF
# This file was generated by the scripts in https://github.com/pantsbuild/pants/tree/master/build-support/native-image/.
# DO NOT EDIT!!!

jvm_binary(
  name='generated-native-image-binary',
  main='org.pantsbuild.zinc.compiler.Main',
  dependencies=[
    $(sed -Ee 's#^(.*)$#"\1",#g')
  ],
)

jvm_app(
  name='native-image-deps',
  basename='gen-native-image-basename',
  binary=':generated-native-image-binary',
  deployjar=True,
)
EOF
}

# generate the deps jar and reflect config at known locations!!!

function generate_macro_deps_jar {
  extract_macro_target_names_from_pants "$@" \
    | if [[ -f "$GENERATED_BUILD_FILE" ]]; then
    # If the generated BUILD file exists already, pull down buildozer to idempotently add the
    # new deps!
    _buildozer="$(download_buildozer)"
    (xargs -t -P1 -L200 printf "//%s "; echo) | while read -r buildozer_deps_flattened; do
      "$_buildozer" "add dependencies ${buildozer_deps_flattened}" \
                    //generated-reflect-config:generated-native-image-binary
      rc="$?"
      # Buildozer will return with 3 if no changes were made and everything exited successfully!
      if ! [[ "$rc" -eq 3 || "$rc" -eq 0 ]]; then
        return "$rc"
      fi
    done
  else
    # Otherwise, generate a BUILD file next to the generated native-image json config.
    template_BUILD_file >"$GENERATED_BUILD_FILE" || return "$?"
  fi >&2
  # NB: This "gracefully" handles the case of having no macros to add by having pants succeed
  # without outputting any jar. This is passed to the native-image build classpath, which accepts
  # entries that don't exist.
  ./pants -ldebug bundle binary \
          //generated-reflect-config:{generated-native-image-binary,native-image-deps} \
          >&2 \
    && normalize_path dist/generated-native-image-binary.jar
}

# actually build the zinc image!!!

### EXECUTING!
# NB: It's not clear whether it's possible to set the locale in some ubuntu containers, so we
# simply ignore it here.
export PANTS_IGNORE_UNRECOGNIZED_ENCODING=1

bootstrap_environment >&2

export JAVA_HOME="$(extract_openjdk_jvmci)"
PATH="$(clone_mx):${PATH}"

readonly ZINC_GENERATED_CONFIG_DIR="$(run_zinc_compile_with_tracing "$@")"
with_pushd "$ZINC_GENERATED_CONFIG_DIR" \
           trim_reflection_config_to_just_macros
readonly MACRO_DEPS_JAR="$(generate_macro_deps_jar "$@")"

create_zinc_image \
  -H:ConfigurationFileDirectories="$GENERATED_CONFIG_DIR" \
  -cp "$MACRO_DEPS_JAR" \
  ${NATIVE_IMAGE_EXTRA_ARGS:-} \
  | while read -r image_location; do
  "$image_location" --help
  echo
done

# NB: if the native-image build fails, and you see the following in the output:
#
#     Caused by: java.lang.VerifyError: class scala.tools.nsc.Global overrides final method isDeveloper.()Z
#
# Please re-run the script at most two more times. This can occur nondeterministically for some
# reason right now.
