python_tests(
  dependencies=[
    'src/python/pants/backend/codegen/thrift/lib',
    'contrib/node/src/python/pants/contrib/node/targets:node_modules',
    'contrib/node/src/python/pants/contrib/node/targets:node_thrift_library',
  ]
)