# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='scalajs',
  dependencies=[
    'contrib/scalajs/src/python/pants/contrib/scalajs/subsystems',
    'contrib/scalajs/src/python/pants/contrib/scalajs/targets',
    'contrib/scalajs/src/python/pants/contrib/scalajs/tasks',
    'src/python/pants/build_graph',
    'src/python/pants/goal:task_registrar',
  ],
  sources=globs('*.py'),
)
