# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Substitutions for classes with static methods, which aren't available in Scala.
java_library(name='statics')

scala_library()
