# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/backend/native/subsystems/platform_specific/linux',
    'src/python/pants/binaries:binary_util',
    'src/python/pants/binaries:execution_environment_mixin',
    'src/python/pants/subsystem',
    'src/python/pants/util:contextutil',
    'src/python/pants/util:memo',
    'src/python/pants/util:osutil',
    'src/python/pants/util:process_handler',
  ],
)
