# coding=utf-8
# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/backend/native/config',
    'src/python/pants/backend/native/subsystems/binaries',
    'src/python/pants/backend/native/subsystems/utils',
    'src/python/pants/backend/python/subsystems',
    'src/python/pants/build_graph',
    'src/python/pants/engine:rules',
    'src/python/pants/engine:selectors',
    'src/python/pants/subsystem',
    'src/python/pants/util:memo',
  ],
)
