# Copyright 2023 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

package_json(
    scripts=[
        node_test_script(
            coverage_args=["--coverage", "--coverage-directory=.coverage/"],
            coverage_output_files=[".coverage/lcov-report/index.html"],
            coverage_output_directories=[".coverage/lcov-report"],
        )
    ]
)
