# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  name = 'backend',
  dependencies = [
    'tests/python/pants_test/backend/codegen',
    'tests/python/pants_test/backend/core',
    'tests/python/pants_test/backend/jvm',
    'tests/python/pants_test/backend/project_info',
    'tests/python/pants_test/backend/python',
  ]
)
