# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_test_suite(
  name = 'backend',
  dependencies = [
    pants('tests/python/pants_test/backend/core'),
    pants('tests/python/pants_test/backend/jvm/tasks/jvm_compile'),
  ]
)
