# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

scala_library(name='consumer',
  dependencies=['testprojects/src/scala/org/pantsbuild/testproject/scalac/plugin'],
  sources=['PluginConsumer.scala'],
)
