# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_binary(
  sources = ['main.py'],
  dependencies = [':lib'],
  tags = {"nolint"},
)

python_library(
  name='lib',
  sources = ['__init__.py'],
  tags = {"nolint"},
)
