# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
  name = 'resourcejars',
  sources = ['ResourceJars.java'],
  dependencies=['3rdparty:junit'],
  resources=['testprojects/tests/resources']
)
