# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    'src/python/pants/base:build_environment',
    'src/python/pants/base:exceptions',
    'src/python/pants/base:workunit',
    'src/python/pants/option',
    'src/python/pants/task',
    'src/python/pants/util:memo',
    'src/python/pants/util:ordered_set',
  ],
  tags = {"partially_type_checked"},
)
