# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'contrib/python/src/python/pants/contrib/python/checks/tasks',
    'src/python/pants/base:deprecated',
  ]
)
