# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_library(
  name = 'plugin',
  dependencies = [
    'src/python/pants/backend/docgen/targets',
    'src/python/pants/backend/docgen/tasks',
    'src/python/pants/build_graph',
    'src/python/pants/engine:addresses',
    'src/python/pants/engine:target',
    'src/python/pants/goal:task_registrar',
  ],
  tags = {"partially_type_checked"},
)
