# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'hello_directory',
  sources = ['hello/**/*'],
)

files(
  name = 'names_directory',
  sources = ['names/**/*'],
)
