# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='aggregated_timings',
  sources=['aggregated_timings.py'],
)

python_library(
  name='pantsd_stats',
  sources=['pantsd_stats.py'],
)

python_library(
  name='run_tracker',
  sources=['run_tracker.py'],
)
