# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  name = 'protobuf-deps',
  dependencies = [
    'contrib/go/examples/3rdparty/go/github.com/golang/protobuf:proto',
    'contrib/go/examples/3rdparty/go/google.golang.org/grpc',
    'contrib/go/examples/3rdparty/go/golang.org/x/net:http2',
  ]
)