# coding=utf-8
# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

android_resources(name='hello',
  manifest=pants('src/android/example/AndroidManifest.xml'),
)

