# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'contrib/thrifty/src/python/pants/contrib/thrifty',
    'src/python/pants/testutil:task_test_base',
  ],
  tags = {'partially_type_checked'},
)
