# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests()

python_integration_tests(
  name='integration',
  uses_pants_run=True,
)
