# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
  name='none',
  sources=['NoWarnings.java']
)

java_library(
  name='empty',
  sources=['Empty.java']
)

java_library(
  name='warning',
  sources=['ReferenceEqualityWarning.java']
)

java_library(
  name='error',
  sources=['ArrayToStringError.java']
)
