# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Demonstrates compiling code with a unicode classes

jvm_binary(name = 'main',
  basename = 'unicode',
  dependencies = [
    'src/java/com/pants/testproject/unicode/cucumber'
  ],
  source = 'CucumberMain.java',
  main = 'com.pants.testproject.unicode.main.CucumberMain',
)
