# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    dependencies=[
        "src/python/pants/backend/go/go_sources/analyze_package",
        "src/python/pants/backend/go/go_sources/asm_check",
        "src/python/pants/backend/go/go_sources/embedcfg",
        "src/python/pants/backend/go/go_sources/generate_testmain",
        "src/python/pants/backend/go/go_sources/parse_vendor_modules",
    ],
)
