# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    basename = "jaxb-example",
    main = "org.pantsbuild.example.jaxb.main.ExampleJaxb",
    source = "ExampleJaxb.java",
    dependencies = [
        "examples/src/java/org/pantsbuild/example/jaxb/reader",
        "examples/src/resources/org/pantsbuild/example/jaxb",
    ],
)
