# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'pants_daemon_client',
  sources = ['pants_daemon_client.py'],
)

python_library(
  name = 'pants_daemon_core',
  sources = ['pants_daemon_core.py'],
)

python_library(
  name = 'pants_daemon',
  sources = ['pants_daemon.py'],
)

python_library(
  name = 'process_manager',
  sources = ['process_manager.py'],
)
