# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='tests',
  timeout = 360,
  dependencies=[
    # Used by `test_options_initializer`.
    "//BUILD_ROOT:files",
  ],
)

python_sources()
