python_tests(
  dependencies = [
    '3rdparty/python:future',
    'contrib/googlejavaformat/src/python/pants/contrib/googlejavaformat',
    'src/python/pants/backend/jvm:plugin',
    'src/python/pants/backend/jvm/targets:java',
    'src/python/pants/base:exceptions',
    'src/python/pants/build_graph',
    'tests/python/pants_test/jvm:nailgun_task_test_base',
  ],
)
