# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_tests(
  name='junit-console-runner',
  dependencies=[
    'tests/java/org/pantsbuild/tools/junit/lib:test-dep',
  ],
  sources=globs('*.java'),
  strict_deps=False,
)
