# Copyright 2023 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

resources(sources=["package-lock.json", "pnpm-lock.yaml", "yarn.lock"])
