# Copyright 2023 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Delete and re-generate these files using the following commands (updating versions as needed):
# corepack npm@11.6.2 install --package-lock-only
# corepack pnpm@10.19.0 install --lockfile-only
# corepack yarn@1.22.22 install --mode update-lockfile
resources(sources=["package-lock.json", "pnpm-lock.yaml", "yarn.lock"])
