# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'src/python/pants/backend/jvm/targets:java',
    'src/python/pants/backend/jvm/tasks/coverage',
    'src/python/pants/java/jar',
    'tests/python/pants_test/backend/jvm/tasks:jvm_binary_task_test_base',
  ]
)