# coding=utf-8
# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

android_library(
  name='google-play-services_lib',
  manifest='AndroidManifest.xml',
  dependencies=[
    ':resources',
    '3rdparty/android:google-play-services'
  ],
)

android_resources(
  name='resources',
  manifest='AndroidManifest.xml',
  resource_dir='res'
)
