# Copyright 2023 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_sources(dependencies=["src/python/pants/backend/python/framework/django/scripts"])

python_tests(name="tests")
