# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

resources(
    name="greeting",
    sources=["greeting.txt"],
)

python_sources(dependencies=[":greeting"])
