# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_tests(
  dependencies = [
    'src/python/pants/backend/codegen/ragel/java',
    'src/python/pants/util:contextutil',
    'tests/python/pants_test/tasks:task_test_base',
  ],
)
