# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
  dependencies=[
    '3rdparty:guava',
    '3rdparty:junit',
    '3rdparty:scalatest',
    'contrib/scalajs/examples/src/scala/org/pantsbuild/scalajs/example/factfinder',
  ],
)
