node_module(
  name='web-component-button',
  sources=globs('package.json', 'webpack.config.js', 'src/*', 'test/*'),
  dependencies=[
    'contrib/node/examples/3rdparty/node/mocha',
    'contrib/node/examples/3rdparty/node/react',
    'contrib/node/examples/src/node/web-build-tool',
  ]
)
