scala_library(
  name='zinc',
  provides=scala_artifact(
    org='org.pantsbuild',
    name='zinc',
    repo=public,
    publication_metadata=pants_library('The SBT incremental compiler for nailgun')
  ),
  dependencies=[
    '3rdparty/jvm/com/typesafe/sbt:incremental-compiler',
    '3rdparty:guava',
    'src/scala/org/pantsbuild/zinc/cache',
    'src/scala/org/pantsbuild/zinc/logging',
    'src/scala/sbt/compiler/javac',
    'src/scala/sbt/inc',
  ],
  sources=globs('*.scala'),
  strict_deps=True,
)
