# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'cache',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:requests',
    '3rdparty/python:six',
    'src/python/pants/base:build_environment',
    'src/python/pants/base:validation',
    'src/python/pants/subsystem',
    'src/python/pants/util:contextutil',
    'src/python/pants/util:dirutil',
    'src/python/pants/util:meta',
  ],
)
