# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    '3rdparty/python:dataclasses',
    'src/python/pants/engine/legacy:structs',
    'src/python/pants/engine:rules',
    'src/python/pants/rules/core',
  ],
  tags = {"type_checked"},
)
