# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name='wsdl_tests_directory',
  sources=['tests/wsdl/**/*'],
)
