# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_tests(
  name='buildozer',
  sources=['test_buildozer.py'],
  dependencies=[
    'contrib/buildozer/src/python/pants/contrib/buildozer:buildozer',
    'src/python/pants/backend/jvm/targets:java',
    'tests/python/pants_test/tasks:task_test_base',
  ]
)
