# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library()

python_tests(
  name='tests',
  dependencies=[
    ':migration-support',
    'src/python/pants/testutil:test_base',
    'src/python/pants/util:contextutil',
  ],
)
