python_library(
  name = 'net',
  sources = rglobs('*.py'),
  dependencies = [
    pants('src/python/twitter/common/dirutil'),
    pants('src/python/twitter/common/lang'),
    pants('src/python/twitter/common/quantity'),
    pants('3rdparty/python:requests'),
  ],
)
