# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
    platform = "java8",
    strict_deps = True,
    dependencies = [
        "3rdparty:guava",
        "3rdparty:jsr305",
        "3rdparty:junit",
        "3rdparty:scalatest",
        "3rdparty/jvm/org/scala-sbt:io",
        "3rdparty/jvm/org/scala-sbt:util-logging",
        "3rdparty/jvm/org/scala-sbt:zinc",
        "src/scala/org/pantsbuild/zinc/analysis",
        "src/scala/org/pantsbuild/zinc/cache",
    ],
)
