# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# NB: This target is written into an .ipex file as the main script, and should not have any
# dependencies on another python code! .ipex files should always contain pex and setuptools
# requirements in order to run the main script!
python_library()
