# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'global_options',
  sources = ['test_global_options.py'],
  coverage = ['pants.option.subsystem.global_options'],
  dependencies = [
    'src/python/pants/option/subsystem:global_options',
    'tests/python/pants_test/subsystem:subsystem_utils',
    'tests/python/pants_test:base_test'
  ]
)
