# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='antlr4',
  source='ExampleAntlr4.java',
  main='com.pants.examples.antlr4.ExampleAntlr4',
  dependencies=[
    'examples/src/antlr/com/pants/examples/exp:exp_antlr4',
  ],
)

