# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/subsystem',
    'src/python/pants/testutil/option',
  ],
  tags = {"partially_type_checked"},
)
