# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(name='codegen',
  dependencies=[
    'tests/python/pants_test/backend/codegen/targets',
    'tests/python/pants_test/backend/codegen/tasks',
  ],
)


