# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(name='missingdepswhitelist',
  sources=rglobs('*.java'),
  dependencies=[
    'examples/src/java/com/pants/examples/hello/greet',
    'testprojects/src/java/com/pants/testproject/missingdepswhitelist2'
  ]
)
