# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='distance',
  basename='protobuf-example',
  dependencies=[
    'examples/src/protobuf/com/pants/examples/distance',
    '3rdparty:protobuf-java',
  ],
  source='ExampleProtobuf.java',
  main='com.pants.examples.protobuf.distance.ExampleProtobuf',
)

