# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'buildfile_path_directory',
  sources = ['buildfile_path/**/*'],
)

files(
  name = 'bundleresources_directory',
  sources = ['bundleresources/**/*'],
)

files(
  name = 'ideacodeandresources_directory',
  sources = ['ideacodeandresources/**/*'],
)

files(
  name = 'idearesourcesonly_directory',
  sources = ['idearesourcesonly/**/*'],
)
