# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_tests(name='compiler',
  sources=globs('*.java'),
  dependencies=[
    '3rdparty:easymock',
    '3rdparty:guava',
    '3rdparty:junit',
    'src/java/org/pantsbuild/testing',
    'src/java/org/pantsbuild/tools/compiler:compiler'
  ]
)
