# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    basename = "wire-temperature-example",
    main = "org.pantsbuild.example.pants.temperatureservice.WireTemperatureExample",
    source = "WireTemperatureExample.java",
    dependencies = [
        "3rdparty:wire-runtime",
        "examples/src/wire/org/pantsbuild/example/temperature",
    ],
)
