# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    basename = "utf8proto-example",
    main = "org.pantsbuild.testproject.utf8proto.ExampleUtf8Proto",
    source = "ExampleUtf8Proto.java",
    dependencies = [
        "3rdparty:protobuf-java",
        "testprojects/src/protobuf/org/pantsbuild/testproject/utf8proto",
    ],
)
