scala_library(
    sources = ["Hello.scala"],
    provides = scala_artifact(
        name = "classifiers",
        org = "org.pantsbuild.testproject.publish",
        publication_metadata = pants_library("This is a test. This is only a test."),
        repo = testing,
    ),
    dependencies = [
    ],
)
