scala_library(
  provides=scala_artifact(
    org='org.pantsbuild.testproject.publish',
    name='classifiers',
    repo=testing,
    publication_metadata=pants_library('This is a test. This is only a test.')
  ),
  dependencies=[
  ],
  sources=['Hello.scala']
)
