# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

go_package(
    import_path="github.com/toolchainlabs/toolchain/src/go/src/toolchain/pants_test/bar",
)

