# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    '3rdparty/python:wheel',
    'src/python/pants/backend/native',
    'src/python/pants/backend/python/tasks',
    'src/python/pants/python',
    'src/python/pants/util:collections',
    'src/python/pants/util:enums',
    'src/python/pants/util:meta',
    'tests/python/pants_test/backend/python/tasks:python_task_test_base',
    'tests/python/pants_test/engine:scheduler_test_base',
  ],
  tags = {"partially_type_checked"},
)
