python_library(
  dependencies=[
    'src/python/pants/backend/native',
    'src/python/pants/backend/python/tasks',
    'tests/python/pants_test/backend/python/tasks:python_task_test_base',
    'tests/python/pants_test/engine:scheduler_test_base',
  ]
)
