page(
  name='index',
  source='index.md',
  links=[
    ':list_goals',
    ':list_targets',
    ':compile',
  ]
)

page(
  name='compile',
  source='compile.md',
)

page(
  name='list_goals',
  source='list_goals.md',
)

page(
  name='list_targets',
  source='list_targets.md'
)
