page(
  name='alias',
  sources=['alias.md'],
)

page(
  name='bundle',
  sources=['bundle.md'],
)

page(
  name='clean',
  sources=['clean.md'],
)

page(
  name='cli_args',
  sources=['cli_args.md'],
)

page(
  name='common_tasks',
  sources=['index.md'],
)

page(
  name='compile',
  sources=['compile.md'],
)

page(
  name='dependencies',
  sources=['dependencies.md'],
)

page(
  name='file_bundles',
  sources=['file_bundles.md'],
)

page(
  name='globs',
  sources=['globs.md'],
)

page(
  name='jvm_binary',
  sources=['jvm_binary.md'],
)

page(
  name='jvm_library',
  sources=['jvm_library.md'],
)

page(
  name='jvm_options',
  sources=['jvm_options.md'],
)

page(
  name='jvm_tests',
  sources=['jvm_tests.md'],
)

page(
  name='list_goals',
  sources=['list_goals.md'],
)

page(
  name='list_targets',
  sources=['list_targets.md']
)

page(
  name='login',
  sources=['login.md']
)

page(
  name='multiple_jvm_versions',
  sources=['multiple_jvm_versions.md'],
)

page(
  name='pex',
  sources=['pex.md'],
)

page(
  name='python_library',
  sources=['python_library.md'],
)

page(
  name='python_tests',
  sources=['python_tests.md'],
)

page(
  name='repl',
  sources=['repl.md'],
)

page(
  name='resources',
  sources=['resources.md'],
)

page(
  name='run',
  sources=['run.md']
)

page(
  name='server',
  sources=['server.md'],
)

page(
  name='target_aggregate',
  sources=['target_aggregate.md'],
)

page(
  name='test',
  sources=['test.md'],
)

page(
  name='test_suite',
  sources=['test_suite.md'],
)

page(
  name='thrift_gen',
  sources=['thrift_gen.md'],
)


page(
  name='python_proto_gen',
  sources=['python_proto_gen.md'],
)
