# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'list_integration',
  sources = ['test_list_integration.py'],
  dependencies = [
    'tests/python/pants_test:int-test'
  ],
  tags = {'integration'},
  timeout = 90,
)
