# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
  dependencies = [
   'examples/src/scala/org/pantsbuild/example/scala_with_java_sources',
  ],
)
