# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library()

python_distribution(
    name="dist",
    provides=python_artifact(
        name="hello",
        version="1.0.0",
    ),
    pypi_repositories=["@foo-bar"],
)
