# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'scala_js_link',
  sources = ['scala_js_link.py'],
  dependencies = [
    ':nailgun_task',
    'src/python/pants/backend/core/tasks:task',
  ],
)
