# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(name='cucumber',
  sources=globs('*.java'),
  dependencies=[
    pants('3rdparty:junit'),
    pants('src/java/com/pants/testproject/unicode/cucumber'),
  ],
)
