# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# This BUILD file contains several targets with scala libraries that can be compiled in parallel.

scala_library(
  name='simple_greeting',
  sources=['simple_greeting.scala'],
)

scala_library(
  name='greeting_by_name',
  sources=['greeting_by_name.scala'],
)

scala_library(
  name='greeting_everybody',
  sources=['greeting_everybody.scala'],
)
