# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'subsystem',
  sources = globs('*.py'),
  dependencies = [
    'src/python/pants/option',
    'src/python/pants/util:meta',
    ],
  )
