# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'plugin',
  sources = ['__init__.py', 'register.py'],
  dependencies = [
    'src/python/pants/base:exceptions',
    'src/python/pants/engine:addressable',
    'src/python/pants/engine:console',
    'src/python/pants/engine:rules',
    'src/python/pants/engine:selectors',
  ]
)
