# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).
#
#  Test project for resource mapping feature

jvm_binary(
    basename = "annotation-example",
    main = "org.pantsbuild.testproject.annotation.main.Main",
    source = "Main.java",
    dependencies = [
        "testprojects/src/java/org/pantsbuild/testproject/annotation/processor",
    ],
)
