# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'antlr_directory',
  sources = rglobs('antlr/*'),
  dependencies = [
    'testprojects/src/antlr/python:test_directory',
  ],
)

files(
  name = 'build_file_imports_function_directory',
  sources = rglobs('build_file_imports_function/*'),
)

files(
  name = 'build_file_imports_module_directory',
  sources = rglobs('build_file_imports_module/*'),
)

files(
  name = 'coordinated_runs_directory',
  sources = rglobs('coordinated_runs/*'),
)

files(
  name = 'interpreter_selection_directory',
  sources = rglobs('interpreter_selection/*'),
)

files(
  name = 'plugins_directory',
  sources = rglobs('plugins/*'),
)

files(
  name = 'print_env_directory',
  sources = rglobs('print_env/*'),
)

files(
  name = 'python_distribution_directory',
  sources = rglobs('python_distribution/*'),
)


files(
  name = 'python_targets_directory',
  sources = rglobs('python_targets/*'),
  dependencies = [
    'testprojects/src/python/python_targets:test',
  ],
)

files(
  name = 'unicode_directory',
  sources = rglobs('unicode/*'),
)
