page(
  name='readme',
  source='readme.md',
  links=[
    ':3rdparty_py',
    ':python_old',
    'src/docs:first_concepts',
  ]
)

page(
  name='3rdparty_py',
  source='3rdparty_py.md',
  links=[
    'src/docs:3rdparty'])

page(
  name='pex_design',
  source='pex_design.md'
)

page(
  name='python_old',
  source='python_old.md',
  links=[
    'src/docs:first_concepts',
    'src/docs:install',
  ]
)