page(
  name='notes-master',
  source='master.rst'
)

page(
  name='notes-1.0.x',
  source='1.0.x.rst'
)

page(
  name='notes-1.1.x',
  source='1.1.x.rst'
)

page(
  name='notes-1.2.x',
  source='1.2.x.rst'
)

page(
  name='notes-1.3.x',
  source='1.3.x.rst'
)

page(
  name='notes-1.4.x',
  source='1.4.x.rst'
)

page(
  name='notes-1.5.x',
  source='1.5.x.rst'
)

page(
  name='notes-1.6.x',
  source='1.6.x.rst'
)

page(
  name='notes-1.7.x',
  source='1.7.x.rst'
)

page(
  name='notes-1.8.x',
  source='1.8.x.rst'
)

page(
  name='notes-1.9.x',
  source='1.9.x.rst'
)

page(
  name='notes-1.10.x',
  source='1.10.x.rst'
)

page(
  name='notes-1.11.x',
  source='1.11.x.rst'
)

page(
  name='notes-1.12.x',
  source='1.12.x.rst'
)

page(
  name='notes-1.13.x',
  source='1.13.x.rst'
)

page(
  name='notes-1.14.x',
  source='1.14.x.rst'
)
