# NB: While we don't use this page anymore, we keep it to avoid broken URLs.
page(
  name='notes-master',
  sources=['master.rst']
)

page(
  name='notes-1.0.x',
  sources=['1.0.x.rst']
)

page(
  name='notes-1.1.x',
  sources=['1.1.x.rst']
)

page(
  name='notes-1.2.x',
  sources=['1.2.x.rst']
)

page(
  name='notes-1.3.x',
  sources=['1.3.x.rst']
)

page(
  name='notes-1.4.x',
  sources=['1.4.x.rst']
)

page(
  name='notes-1.5.x',
  sources=['1.5.x.rst']
)

page(
  name='notes-1.6.x',
  sources=['1.6.x.rst']
)

page(
  name='notes-1.7.x',
  sources=['1.7.x.rst']
)

page(
  name='notes-1.8.x',
  sources=['1.8.x.rst']
)

page(
  name='notes-1.9.x',
  sources=['1.9.x.rst']
)

page(
  name='notes-1.10.x',
  sources=['1.10.x.rst']
)

page(
  name='notes-1.11.x',
  sources=['1.11.x.rst']
)

page(
  name='notes-1.12.x',
  sources=['1.12.x.rst']
)

page(
  name='notes-1.13.x',
  sources=['1.13.x.rst']
)

page(
  name='notes-1.14.x',
  sources=['1.14.x.rst']
)

page(
  name='notes-1.15.x',
  sources=['1.15.x.rst']
)

page(
  name='notes-1.16.x',
  sources=['1.16.x.rst']
)

page(
  name='notes-1.17.x',
  sources=['1.17.x.rst']
)

page(
  name='notes-1.18.x',
  sources=['1.18.x.rst']
)

page(
  name='notes-1.19.x',
  sources=['1.19.x.rst']
)

page(
  name='notes-1.20.x',
  sources=['1.20.x.rst']
)

page(
  name='notes-1.21.x',
  sources=['1.21.x.rst']
)

page(
  name='notes-1.22.x',
  sources=['1.22.x.rst']
)

page(
  name='notes-1.23.x',
  sources=['1.23.x.rst']
)

page(
  name='notes-1.24.x',
  sources=['1.24.x.rst']
)

page(
  name='notes-1.25.x',
  sources=['1.25.x.rst']
)

page(
  name='notes-1.26.x',
  sources=['1.26.x.rst']
)

page(
  name='notes-1.27.x',
  sources=['1.27.x.rst']
)

page(
  name='notes-1.28.x',
  sources=['1.28.x.rst']
)

page(
  name='notes-1.29.x',
  sources=['1.29.x.rst']
)

page(
  name='notes-1.30.x',
  sources=['1.30.x.rst']
)
