page(
  name='notes-master',
  source='master.rst'
)

page(
  name='notes-1.0.x',
  source='1.0.x.rst'
)

page(
  name='notes-1.1.x',
  source='1.1.x.rst'
)

page(
  name='notes-1.2.x',
  source='1.2.x.rst'
)

page(
  name='notes-1.3.x',
  source='1.3.x.rst'
)
