# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    main = "org.pantsbuild.example.antlr4.ExampleAntlr4",
    source = "ExampleAntlr4.java",
    strict_deps = False,
    dependencies = [
        "examples/src/antlr/org/pantsbuild/example/exp:exp_antlr4",
    ],
)
