# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='isort',
  sources=globs('*.py'),
  dependencies=[
    '3rdparty/python:isort',
    'src/python/pants/backend/python/tasks:python',
    'src/python/pants/option',
  ]
)
