# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='scalajs_repl_integration',
  sources=['test_scalajs_repl_integration.py'],
  dependencies = [
    'tests/python/pants_test:int-test',
  ],
  tags={'integration'},
)
