python_library(
  name = 'cache',
  sources = globs('*.py'),
  dependencies = [
    pants('src/python/twitter/common/contextutil'),
    pants('src/python/twitter/common/dirutil'),
    pants('src/python/twitter/common/quantity'),
  ]
)
