# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'passing_target',
  sources = ['test_sleep.py'],
  timeout = 3,
)

python_tests(
  name = 'failing_target',
  sources = ['test_sleep.py'],
  timeout = 1,
)
