# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'sleeping_target',
  sources = ['test_sleep.py'],
)

python_tests(
  name = 'ignore_terminate_target',
  sources = ['test_ignore_terminate.py']
)