# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'sleeping_target',
  sources = ['test_sleep.py'],
)

python_tests(
  name = 'must_kill_target',
  sources = ['test_handle_term.py']
)