# coding=utf-8
# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/backend/native/config',
    'src/python/pants/backend/native/subsystems/utils',
    'src/python/pants/binaries',
    'src/python/pants/engine:rules',
    'src/python/pants/engine:platform',
    'src/python/pants/util:dirutil',
    'src/python/pants/util:enums',
    'src/python/pants/util:memo',
  ],
  tags = {"partially_type_checked"},
)
