# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

resource(
    name="dependency_parser",
    source="dependency_parser.py",
)

# Also expose script as a python source so it gets formatted/linted/checked.
python_source(
    name="dependency_parser_source",
    source="dependency_parser.py",
)
