# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    ':text',
  ],
  sources=['*.py'],
)

resources(
  name='text',
  sources=['*.txt'],
)
