# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  # TODO: Some tests in tests/python/pants_test/engine/legacy:changed_integration
  # (e.g., test_changed_coverage_direct_src_python_sources_sources_py) fail if this
  # target doesn't have an explicit sources= stanza.  Figure out why, and fix.
  sources=globs('*.py'),
)
