# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='forced_native_bdist',
  sources=['src.py'],
  provides=setup_py(
    name='forced_native_bdist',
    description='An example for forcing native wheel builds in the setup-py goal.',
    version='1.0.0',
    force_native=True
  )
)
