# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    basename = "protobuf-example",
    main = "org.pantsbuild.example.protobuf.distance.ExampleProtobuf",
    source = "ExampleProtobuf.java",
    dependencies = [
        "3rdparty:protobuf-java",
        "examples/src/protobuf/org/pantsbuild/example/distance",
    ],
)
