python_library(
  name = 'ivy',
  sources = globs('*.py'),
  dependencies = [
    pants('src/python/twitter/common/collections'),
    pants('src/python/twitter/common/contextutil'),
    pants('src/python/twitter/common/dirutil'),
    pants('src/python/twitter/common/lang'),
    pants('src/python/twitter/common/log'),
    pants('src/python/twitter/common/quantity'),
    pants('src/python/twitter/pants/base:config'),
    pants('src/python/twitter/pants/java:executor'),
    pants('src/python/twitter/pants/java:util'),
    pants('src/python/twitter/pants/net'),
  ]
)
