# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    dependencies=[":docker_shim"],
)

resource(name="docker_shim", source="docker_shim.sh")

shell_sources(
    name="shell",
)
