# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'git_hooks',
  dependencies = [
    'src/python/pants/util:contextutil',
    'src/python/pants/util:dirutil',
    'tests/python/pants_test/testutils:git_util',
    'build-support/bin:check_header',
    'build-support/bin:check_packages',
    'build-support/bin:get_added_files',
  ]
)
