# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
  # Keep the name until https://github.com/pantsbuild/intellij-pants-plugin/issues/211
  # is resolved.
  name = 'missingdepswhitelist2',
  sources=rglobs('*.java'),
)
