# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    '3rdparty/python:setuptools',
    'src/python/pants/binaries:execution_environment_mixin',
    'src/python/pants/backend/native',
    'src/python/pants/option',
    'src/python/pants/subsystem',
    'src/python/pants/util:memo',
  ],
)
