# Auto-generated by pants!
# To re-generate run: `pants buildgen.go --materialize --remote`

go_library(
  dependencies=[
    'contrib/go/examples/src/go/libD',
    'contrib/go/examples/src/go/libE',
  ]
)
