# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_library(
  sources = globs('confluence_util.py'),
  dependencies = [
    '3rdparty/python/twitter/commons:twitter.common.log'
  ],
)
