# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

# relocated_files(
#     name="frontend-files",
#     files_targets=["src/javascript/explorer:dist-files"],
#     src="src/javascript/explorer/dist",
#     dest="src/python/pants/backend/explorer/server/files"
# )

# python_distribution(
#     name="dist",
#     dependencies=[":server", ":frontend-files"],
#     provides=python_artifact(
#         name="pantsbuild.pants.explorer.api-server",
#         description="Backend API server implementation for the Pants Explorer UI.",
#         classifiers=["Topic :: Software Development"],
#     ),
#     entry_points={
#         "pantsbuild.plugin": {
#             "rules": "pants.backend.explorer.server.register:rules",
#         }
#     },
# )
