# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

dependencies(name='missing-build-file',
  dependencies=[':malformed-target'],
)

dependencies(name='malformed-target',
  dependencies=['/testprojects/maven_layout/missing-build-file/no-such-build-file']
)
