# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_avro_library(
  name='simple',
  sources=['simple.avdl'],
)

java_avro_library(
  name='user',
  sources=['user.avsc'],
)
