# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

scala_library(
  provides=scala_artifact(
    org='org.pantsbuild',
    name='zinc-scalautil',
    repo=public,
    publication_metadata=pants_library('Common utilities to create objects required by the zinc wrappers.')
  ),
  dependencies = [
    'src/scala/org/pantsbuild/zinc/util',
  ]
)
