# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    '3rdparty/python:future',
    'src/python/pants/backend/codegen/thrift/lib',
    'src/python/pants/backend/python/targets:python',
    'src/python/pants/base:exceptions',
    'src/python/pants/engine:fs',
    'src/python/pants/goal:task_registrar',
    'src/python/pants/task:task',
    'src/python/pants/util:collections_abc_backport',
  ],
)
