# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  sources=['source_root.py'],
)

python_library(
  name = "filespec",
  sources = ["filespec.py"],
)

python_tests(name='tests')
