java_thrift_library(
  name = 'android_generator',
  sources = ['struct.thrift'],
  dependencies = ['3rdparty:scrooge-core',
                  '3rdparty:thrift-0.9.2'],
  compiler='scrooge',
  language='android',
  rpc_style='finagle'
)


