# Copyright 2023 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

tsx_tests(
    name="tests",
    dependencies=["testprojects/src/ts/hello_react_ts/src:setupTests"],
)
