# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='service',
  dependencies=[
    'examples/src/protobuf/com/pants/examples/service',
    '3rdparty:protobuf-java',
  ],
  source='ExampleService.java',
  main='com.pants.examples.protobuf.ExampleService',
)

