# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='main',
  dependencies=[
    'src/java/com/pants/examples/jaxb/reader',
    'src/resources/com/pants/example/names',
  ],
  source='ExampleJaxb.java',
  main='com.pants.examples.jaxb.main.ExampleJaxb',
)
