# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='buildozer',
  sources=['test_buildozer.py'],
  dependencies=[
    'src/python/pants/backend/jvm/targets:java',
    'src/python/pants/backend/python/buildozer:buildozer',
    'tests/python/pants_test/tasks:task_test_base', 
  ]
)
