# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_protobuf_library(name='proto',
  sources=globs('*.proto'),
  dependencies=[
    'src/protobuf/com/pants/examples/distance:proto',
  ],
)
