java_library(name='cycle2',
             dependencies=[
               '3rdparty:log4j',
               'testprojects/src/java/org/pantsbuild/testproject/cycle1',
             ],
             sources = ['Bar.java'],
)
