# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

go_protobuf_library(name='grpc-go',
                    # dependencies=[
                    #   'contrib/go/examples/3rdparty/go/google.golang.org/grpc',
                    # ],
                    protoc_plugins=['grpc'])

