# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='externalarchive',
  source='ExampleProtobufExternalArchive.java',
  main='com.pants.examples.protobuf.externalarchive.ExampleProtobufExternalArchive',
  dependencies=[
    'examples/src/protobuf/com/pants/examples/externalarchive'
  ],
)
