# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

source_root('3rdparty', jar_library)
source_root('src/python', page, python_binary, python_library, resources)
source_root('tests/jvm', page, scala_library, junit_tests)
source_root('tests/thrift', page, spindle_thrift_library)
