# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='element',
  basename='wire-element-example',
  dependencies=[
    'examples/src/wire/com/pants/examples/element',
  ],
  source='WireElementExample.java',
  main='com.pants.examples.wire.element.WireElementExample',
)

