# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    'src/python/pants/backend/jvm/tasks:scala_rewrite_base',
    'src/python/pants/goal:products',
    'src/python/pants/task',
    'src/python/pants/util:memo',
  ],
)
