scala_library(
  name='fatal',
  compiler_option_sets={'fatal_warnings'},
  fatal_warnings=True,
  sources=['Warning.scala'],
)

scala_library(
  name='nonfatal',
  compiler_option_sets={},
  sources=['Warning.scala'],
)
