scala_library(
  name='fatal',
  sources=['Warning.scala'],
  compile_options=['+fatal_warnings'],
)

scala_library(
  name='nonfatal',
  sources=['Warning.scala'],
  compile_options=['-fatal_warnings'],
)

scala_library(
  name='defaultfatal',
  sources=['Warning.scala'],
)
