# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='exe',
  dependencies=[
    pants('src/scala/com/pants/example/hello/welcome:welcome'),
  ],
  source='Exe.scala',
  main='com.pants.example.hello.exe.Exe',
)