# Copyright 2024 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

__defaults__(all={"resolve": "python-plugins"})

# Support dep inference for `import pytest`
python_requirement(
    name="pytest",
    requirements=["pytest"],
)

pants_requirements()
