# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/testutil/option',
    'tests/python/pants_test:deprecated_testinfra',
  ],
)
