# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    'src/python/pants/backend/codegen/thrift/lib',
    'src/python/pants/backend/jvm:target_types',
    'src/python/pants/backend/jvm/targets:java',
    'src/python/pants/base:exceptions',
    'src/python/pants/build_graph',
    'src/python/pants/goal:task_registrar',
    'src/python/pants/engine:target',
    'src/python/pants/option',
    'src/python/pants/subsystem',
    'src/python/pants/task',
  ],
  tags = {"partially_type_checked"},
)
