# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='global_options',
  sources=globs('*.py'),
  dependencies=[
    'src/python/pants/option',
    'src/python/pants/subsystem',
  ]
)
