# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

scala_js_binary(
  dependencies=[
    'examples/src/scala/org/pantsbuild/example/fact:fact-js',
  ],
  sources=globs('*.scala'),
)
