# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

dependencies(name='pingpong',
  dependencies=[
    pants('tests/java/com/pants/examples/pingpong/handler'),
  ])