# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(name='logging',
  dependencies=[
    'src/scala/org/pantsbuild/zinc/logging',
    '3rdparty:junit',
    '3rdparty:specs',
  ],
  sources=globs('*.scala'),
)
