# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'scala_js_platform',
  sources = ['scala_js_platform.py'],
  dependencies = [
    'src/python/pants/option',
    'src/python/pants/subsystem',
  ],
)
