# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'subsystems',
  dependencies = [
    'src/python/pants/option',
    'src/python/pants/subsystem',
  ],
  sources = globs('*'),
)
