# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='subsystem_utils',
  sources=['subsystem_util.py'],
  dependencies=[
    'src/python/pants/testutil/subsystem',
    'tests/python/pants_test:deprecated_testinfra',
  ],
  tags = {'partially_type_checked'},
)
