# Copyright 2023 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

package_json(name="package.json")

javascript_sources()
javascript_tests(name="tests")

shell_sources(name="shell")

files(name="support_files", sources=["*"])
