# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  name = 'project_info',
  dependencies = [
    'tests/python/pants_test/backend/project_info/tasks:all',
  ]
)
