python_library(
  name='targets',
  sources=globs('*.py'),
  dependencies=[
    '3rdparty/python/twitter/commons:twitter.common.collections',
    '3rdparty/python/twitter/commons:twitter.common.lang',
#    'src/python/pants/base:exceptions',
#    'src/python/pants/base:payload',
#    'src/python/pants/base:payload_field',
#    'src/python/pants/base:target',
  ]
)