python_tests(
  dependencies=[
    'src/python/pants/backend/native',
    'src/python/pants/backend/native/config',
    'src/python/pants/backend/native/subsystems',
    'src/python/pants/backend/native/subsystems/binaries',
    'src/python/pants/engine/internals:scheduler_test_base',
    'src/python/pants/util:contextutil',
    'src/python/pants/util:osutil',
    'src/python/pants/util:strutil',
    'src/python/pants/testutil:test_base',
    'tests/python/pants_test/backend/native/util',
    'src/python/pants/testutil/subsystem',
  ],
  tags={'platform_specific_behavior', 'partially_type_checked'},
  timeout=300,
)
