# coding=utf-8
# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
    dependencies = [
        "src/python/pants/backend/native/subsystems",
        "src/python/pants/util:contextutil",
        "src/python/pants/util:process_handler",
        "tests/python/pants_test:base_test",
        "tests/python/pants_test/subsystem:subsystem_utils",
    ],
)
