page(
  name='readme',
  source='readme.md',
)

page(
  name='credits',
  source='credits.md',
)

page(
  name='dev_tasks',
  source='dev_tasks.md',
)

page(
  name='dev_tasks_publish_extras',
  source='dev_tasks_publish_extras.md',
)

page(
  name='docs',
  source='docs.md',
)

page(
  name='howto_ask',
  source='howto_ask.md',
)

page(
  name='howto_contribute',
  source='howto_contribute.md',
  dependencies=[
    ':docs',
    ':howto_ask',
  ]
)

page(
  name='howto_customize',
  source='howto_customize.md',
  dependencies=[
    ':howto_contribute'
  ]
)

page(
  name='howto_develop',
  source='howto_develop.md',
  dependencies=[
  ]
)

page(
  name='howto_plugin',
  source='howto_plugin.md',
  dependencies=[
    ':docs',
    # TODO    ':howto_develop',
  ]
)

page(
  name='intellij',
  source='intellij.md',
)

page(
  name='internals',
  source='internals.md',
)

page(
  name='release',
  source='release.md',
)

