python_binary(
    name = "test_bin",
    entry_point = "testprojects.src.python.interpreter_selection.test_target_with_no_sources.src.python.test_project",
    compatibility = ["CPython>3"],
    dependencies = [
        "testprojects/src/python/interpreter_selection/test_target_with_no_sources/src/python/test_project",
    ],
)
