# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jaxb_library(
  sources=globs('*.xsd'),
  package='org.pantsbuild.example.jaxb.api',
)
