# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'pants_service',
  sources = ['test_pants_service.py'],
  dependencies = [
    'src/python/pants/pantsd/service:pants_service',
    'src/python/pants/testutil:test_base',
  ],
)
