# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

page(
  name='go_readme',
  sources=['README.md'],
)

files(
  name='examples_directory',
  sources=['examples/**/*'],
)
