# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

source_root('src/python', python_library)
source_root('tests/python', python_library, python_tests)

source_root('examples/3rdparty/go', go_remote_package)
source_root('examples/src/go', go_package, go_binary)