# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'build_parsing_directory',
  sources = rglobs('build_parsing/*'),
)
