# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    dependencies=[
        # TODO: This dependency was not inferred for some (yet unknown) reason.
        "src/python/pants/testutil/lockfile_fixture.py"
    ]
)
