scala_js_binary(
  name='scalajs',
  dependencies=[
    ':scalajs-lib',
  ],
)

scala_js_library(
  name='scalajs-lib',
  sources=globs('*'),
  dependencies=[
    '3rdparty/jvm/org/scala-js:library',
  ],
)
