# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_wire_library(
    # Order matters here:
    sources = [
        "elements.proto",
        "compound.proto",
    ],
    dependencies = [
        "examples/src/wire/org/pantsbuild/example/temperature",
    ],
)
