# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_protobuf_library(name='protos',
  sources=['testproto5.proto', 'testproto6.proto',],
  dependencies=[
    'testprojects/src/protobuf/com/pants/testproject/proto-ordering/a',
    'testprojects/src/protobuf/com/pants/testproject/proto-ordering/b',
  ],
)
