# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# This scala_library() contains two files which depend on one another cyclically: being able to
# compile them both in parallel means supporting outlining.
scala_library()
