# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
  dependencies=[
    '3rdparty:ivy',
    '3rdparty:junit',
    '3rdparty/jvm/org/hamcrest:hamcrest-library',
    'src/java/org/pantsbuild/tools/ivy:ivy-dependency-update-checker',
    'tests/resources/org/pantsbuild/tools/ivy',
  ],
)
