# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jaxb_library(name='jaxb',
  sources=globs('*.xsd'),
  package='com.pants.examples.jaxb.api',
)
