protobuf_source(name="f_proto", source="f.proto", dependencies=["testprojects/src/jvm_proto:protobuf-java"])
protobuf_source(name="f2_proto", source="f2.proto", dependencies=["testprojects/src/jvm_proto:protobuf-java"])
