# coding=utf-8
# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    '3rdparty/python:dataclasses',
    'src/python/pants/backend/native/config',
    'src/python/pants/backend/native/subsystems',
    'src/python/pants/backend/native/subsystems/packaging',
    'src/python/pants/backend/native/targets',
    'src/python/pants/base:build_environment',
    'src/python/pants/base:exceptions',
    'src/python/pants/base:workunit',
    'src/python/pants/build_graph',
    'src/python/pants/task',
    'src/python/pants/util:collections',
    'src/python/pants/util:contextutil',
    'src/python/pants/util:enums',
    'src/python/pants/util:memo',
    'src/python/pants/util:objects',
    'src/python/pants/util:strutil',
  ],
  tags = {"partially_type_checked"},
)
