# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='logging',
  sources=globs('*.py'),
  dependencies = [
    '3rdparty/python:six',
    'src/python/pants/logging',
    'src/python/pants/util:contextutil',
  ],
)
