# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_integration_tests(
  name='tests',
  uses_pants_run=True,
  timeout=150,
)

python_library()
