# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


source_root('examples/src/java', jvm_binary, java_library)
source_root('examples/src/resources', generated_resources, resources)
source_root('src/python', python_library)
source_root('tests/python', python_library, python_tests)
