# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
    cwd = "testprojects/tests/java/org/pantsbuild/testproject/workdirs/twodir",
    dependencies = [
        "3rdparty:junit",
    ],
)
