# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies = [
    '3rdparty/python:mock',
    '3rdparty/python:six',
    'src/python/pants/process',
  ]
)
