import os

# Publicly accessible twitter maven repo that houses twitter-commons artifacts
repo(name = 'public',
     url = 'http://maven.twttr.com',
     push_db_basedir = os.path.join(buildfile_path(), 'pushdb'))

