# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'process',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:fasteners',
    '3rdparty/python:psutil',
    'src/python/pants/util:dirutil',
  ],
)
