# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_binary(
  name='creator',
  sources=['creator.py'],
)

python_binary(
  name='phaser',
  sources=['phaser.py'],
)

python_binary(
  name='waiter',
  sources=['waiter.py'],
)
