# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

pex_binary(name="waiter", entry_point="waiter.py", restartable=True)
