# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

scala_library(
  name = 'scala',
  sources = ['Scala.scala'],
  dependencies = [':scala-2'],
  exports = [':scala-2']
)

scala_library(
  name = 'scala-2',
  sources = ['Scala2.scala']
)
