# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'build_environment',
  sources = ['build_environment.py'],
)

python_library(
  name = 'project_tree',
  sources = ['file_system_project_tree.py', 'project_tree.py'],
)

python_library(
  name = 'build_root',
  sources = ['build_root.py'],
)

python_library(
  name = 'deprecated',
  sources = ['deprecated.py'],
)

python_library(
  name = 'exception_sink',
  sources = ['exception_sink.py'],
)

python_library(
  name = 'exceptions',
  sources = ['exceptions.py'],
)

python_library(
  name = 'fingerprint_strategy',
  sources = ['fingerprint_strategy.py'],
)

python_library(
  name = 'generator',
  sources = ['generator.py'],
)

python_library(
  name = 'hash_utils',
  sources = ['hash_utils.py'],
)

python_library(
  name = 'mustache',
  sources = ['mustache.py'],
)

python_library(
  name = 'parse_context',
  sources = ['parse_context.py'],
)

python_library(
  name = 'payload',
  sources = ['payload.py'],
)

python_library(
  name = 'payload_field',
  sources = ['payload_field.py'],
)

python_library(
  name = 'specs',
  sources = ['specs.py'],
)

python_library(
  name = 'run_info',
  sources = ['run_info.py'],
)

python_library(
  name = 'cmd_line_spec_parser',
  sources = ['cmd_line_spec_parser.py'],
)

python_library(
  name = 'worker_pool',
  sources = ['worker_pool.py'],
)

python_library(
  name = 'workunit',
  sources = ['workunit.py'],
)

python_library(
  name='validation',
  sources=['validation.py'],
)

python_library(
  name='exiter',
  sources=['exiter.py'],
)

python_tests(name='tests')
