# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'netrc',
  sources = ['test_netrc_util.py'],
  dependencies = [
    pants('3rdparty/python:mock'),
    pants('src/python/pants/authentication:authentication'),
  ]
)
