# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_library(
  dependencies=[
    '3rdparty/python:pex',
    '3rdparty/python:setuptools',
    'src/python/pants/base:build_environment',
    'src/python/pants/base:exceptions',
    'src/python/pants/backend/python/subsystems/ipex',
    'src/python/pants/build_graph',
    'src/python/pants/option',
    'src/python/pants/subsystem',
    'src/python/pants/util:memo',
  ]
)
