# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='temperature',
  basename='wire-temperature-example',
  dependencies=[
    'examples/src/wire/com/pants/examples/temperature',
  ],
  source='WireTemperatureExample.java',
  main='com.pants.examples.pants.temperature.WireTemperatureExample',
)

