# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = '3rdparty_directory',
  sources = ['3rdparty/**/*'],
)

files(
  name = 'isort_cfg',
  sources = ['.isort.cfg'],
)
