# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'valid',
  source = 'valid.py',
  tags = {'partially_type_checked'},
)

python_library(
  name = 'invalid',
  source = 'invalid.py',
)
