# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
    name = "X",
    sources = [],
)

java_library(
    name = "A",
    sources = [],
    dependencies = [":X"],
)

java_library(
    name = "B",
    sources = [],
    dependencies = [":X"],
)

java_library(
    name = "C",
    sources = [],
    dependencies = [":X"],
)
