# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
    name = "X"
)

java_library(
    name = "A",
    dependencies = [":X"]
)

java_library(
    name = "B",
    dependencies = [":X"]
)

java_library(
    name = "C",
    dependencies = [":X"]
)
