# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
    name = "Y",
)

java_library(
    name = "A",
    dependencies = [":Y"],
)

java_library(
    name = "B",
    dependencies = [":Y"],
)

java_library(
    name = "C",
    dependencies = [":Y"],
)
