java_sources(
    name = 'main',

    dependencies = [
        'testprojects/src/jvm_proto/lib:lib',
        'testprojects/src/jvm_proto/src/protobuf/dir1:f_proto',
    ]
)


jvm_artifact(
    name = "protobuf-java",
    group = 'com.google.protobuf',
    artifact = 'protobuf-java',
    version = '3.19.0',
)
#implementation group: 'com.google.protobuf', name: 'protobuf-java', version: '3.19.0'
