# Copyright 2024 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

package_json(dependencies=[":tsconfig"])

file(name="tsconfig", source="tsconfig.json")
