# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

python_tests(
    name="config_test",
    sources=["config_test.py"],
)

python_tests(
    name="rules_integration_test",
    sources=["rules_integration_test.py"],
    timeout=480,
)

python_tests(
    name="subsystem_integration_test",
    sources=["subsystem_integration_test.py"],
)

python_tests(
    name="target_types_integration_test",
    sources=["target_types_integration_test.py"],
)
