# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


junit_tests(name='fail256',
  sources=globs('*'),
  dependencies=[
    '3rdparty:junit'
  ],
)
