# Copyright 2024 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(resolve="lock-torch")


python_requirements(
    name="torch",
    source="requirements.txt",
    resolve="lock-torch",
)