# Copyright 2024 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).
python_tests(
    name="tests",
    dependencies=[
        "testprojects/pants-plugins/src/python/python_constant/register.py",
    ],
    timeout=350,
)
