# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_source(name="init", source="__init__.py")
resources(sources=["*.go"], dependencies=[":init"])
