# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

scala_library(
  sources = ['Greet.scala'],
  java_sources=[
    'examples/src/java/org/pantsbuild/example/java_sources',
   ],
)

