# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name='avro_tests_directory',
  sources=['tests/avro/**/*'],
)
