# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# A plugin that logs workunits via a WorkunitsCallback.
python_library()
