# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='lesser-of-two',
  main='com.pants.testproject.phrases.LesserOfTwo',
  source='LesserOfTwo.java',
)

jvm_binary(name='once-upon-a-time',
  main='com.pants.testproject.phrases.OnceUponATime',
  source='OnceUponATime.java',
)

jvm_binary(name='ten-thousand',
  main='com.pants.testproject.phrases.TenThousand',
  source='TenThousand.java',
)

jvm_binary(name='there-was-a-duck',
  main='com.pants.testproject.phrases.ThereWasADuck',
  source='ThereWasADuck.java',
)
