# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    '3rdparty/python:requests',
    'src/python/pants/base:build_environment',
    'src/python/pants/core/util_rules',
    'src/python/pants/engine:platform',
  ],
  tags = {"partially_type_checked"},
)
