python_library(
  dependencies = [
    'src/python/pants/backend/jvm/tasks:classpath_products',
    'src/python/pants/backend/jvm/tasks:nailgun_task',
    'src/python/pants/backend/jvm:ivy_utils',
    'src/python/pants/java/jar',
    'src/python/pants/base:exceptions',
    'src/python/pants/invalidation',
    'src/python/pants/util:desktop',
    'src/python/pants/util:dirutil',
    'src/python/pants/util:strutil',
    'src/python/pants/backend/jvm/subsystems:resolve_subsystem'
  ],
)
