# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'zinc',
  sources = globs('*.py'),
  dependencies = [
    '3rdparty/python:six',
    'src/python/pants/backend/jvm/zinc',
    'src/python/pants/util:contextutil',
  ],
)
