# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_sources(
    dependencies=[
        "//testprojects/src/java/org/pantsbuild/example/app:lockfile",
        "//testprojects/src/java/org/pantsbuild/example/app:com.fasterxml.jackson.core_jackson-databind",
    ]
)