# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='core_tasks',
  sources=globs('*.py'),
  dependencies=[
    'src/python/pants/base:exceptions',
    'src/python/pants/base:workunit',
    'src/python/pants/binaries:binary_util',
    'src/python/pants/goal:task_registrar',
    'src/python/pants/reporting',
    'src/python/pants/task',
    'src/python/pants/util:dirutil',
  ])
