junit_tests(
    sources=globs('*.scala'),
    dependencies=[
      'src/scala/org/pantsbuild/native_image',
      '3rdparty/jvm/org/scalameta:testkit',
      '3rdparty/jvm/io/get-coursier:coursier',
    ]
)
