jvm_binary(
    extra_jvm_options = ['-Dproperty.color=orange', '-Dproperty.size=2'],
    name = 'opts',
    main = 'opts.Main',
    sources = ['Main.java']
)

jvm_binary(
    name = 'no-opts',
    main = 'opts.Main',
    sources = ['Main.java']
)