# Copyright 2025 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    sources=[
        "register.py",
        "rules.py",
        "skip_field.py",
        "subsystem.py",
    ],
)

python_tests(
    name="tests",
)
