# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  dependencies=[':ant'],
)

jar_library(name='ant',
  jars=[
    jar(org='ant', name='ant', rev='1.6.4')
  ],
)
