# Copyright 2023 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).
python_sources(
    # Used for Python 2.7 distributions
    skip_pyupgrade=True,
)
