# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# This target mirrors a likewise target at:
#   testprojects/tests/resources/org/pantsbuild/testproject/bundleresources:resources
# for the purposes of resource ordering testing.

resources(name='resources',
  sources=['resources.txt'],
)
