# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  sources=[
    'jax_ws_library.py',
  ],
  dependencies=[
    'src/python/pants/base:payload_field',
    'src/python/pants/backend/jvm/targets:java',
  ],
)
