# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='imports',
  basename='protobuf-imports-example',
  dependencies=[
    'examples/src/protobuf/com/pants/examples/imports',
    '3rdparty:protobuf-java',
  ],
  source='ExampleProtobufImports.java',
  main='com.pants.examples.protobuf.imports.ExampleProtobufImports',
)
