# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    basename = "protobuf-unpacked-jars-example",
    main = "org.pantsbuild.example.protobuf.unpacked_jars.ExampleProtobufExternalArchive",
    source = "ExampleProtobufExternalArchive.java",
    dependencies = [
        "3rdparty:protobuf-java",
        "examples/src/protobuf/org/pantsbuild/example/unpacked_jars",
    ],
)
