[GLOBAL]
pants_version = "2.32.0rc0"

backend_packages = ["pants.backend.python"]

[python]
interpreter_constraints = ["CPython>=3.10"]
enable_resolves = true
resolver = "uv"

[python.resolves]
bug1 = "bug1/src/bug1.lock"
bug2 = "bug2/src/bug2.lock"

[python-repos]
find_links = ["%(buildroot)s/bug1/wheels", "%(buildroot)s/bug2/wheels"]

[source]
root_patterns = ["/bug1/src", "/bug2/src"]
