junit_tests(
  dependencies = [
    'src/java/org/pantsbuild/tools/junit:security-manager',
    'tests/java/org/pantsbuild/tools/junit/impl:common',
    'tests/java/org/pantsbuild/tools/junit/lib:test-dep',
    'tests/scala/org/pantsbuild/tools/junit/lib:scala-test-dep',
    'tests/resources/org/pantsbuild/tools/junit/lib',
  ]
)
