# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
    platform = "java7",
    provides = artifact(
        name = "junit-runner-annotations",
        org = "org.pantsbuild",
        publication_metadata = pants_library("""
      Annotations for use with org.pantsbuild#junit-runner that support running tests in parallel.
    """),
        repo = public,
    ),
)
