# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
  name='annotations',
  provides=artifact(
    org='org.pantsbuild',
    name='junit-runner-annotations',
    repo=public,
  ),
  sources=globs('*.java')
)
