# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_thrifty_library(
  dependencies=[
    'contrib/thrifty/tests/thrift/org/pantsbuild/contrib/thrifty/common',
  ],
)
