# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    main = "org.pantsbuild.example.hello.exe.Exe",
    source = "Exe.scala",
    dependencies = [
        "examples/src/scala/org/pantsbuild/example/hello/welcome",
    ],
)
