# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

docker_image(
    name="test-example",
    version="1.2.3",
    dependencies=["testprojects/src/python/hello/main"],
)
