# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'fs',
  sources = globs('*.py'),
  dependencies = [
    pants('src/python/pants/fs'),
    pants('src/python/pants/util:contextutil'),
    pants('src/python/pants/util:dirutil'),
  ]
)
