jvm_binary(name = 'jsresources',
  source = 'JsResourcesMain.java',
  main = 'org.pantsbuild.testproject.jsresources.JsResourcesMain',
  dependencies = [
    '3rdparty:guava',
    'contrib/node/examples/src/node/web-component-button',
  ]
)
