# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

BASH_BUILTIN_COMMANDS = (
    "alias",
    "bind",
    "break",
    "builtin",
    "caller",
    "cd",
    "command",
    "continue",
    "declare",
    "echo",
    "enable",
    "eval",
    "exec",
    "exit",
    "export",
    "getopts",
    "hash",
    "help",
    "let",
    "local",
    "logout",
    "mapfile",
    "printf",
    "pwd",
    "read",
    "readarray",
    "readonly",
    "return",
    "shift",
    "source",
    "test",
    "times",
    "trap",
    "type",
    "typeset",
    "ulimit",
    "umask",
    "unalias",
    "unset",
)
