# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(
  name='withretry',
  provides=artifact(
    org='org.pantsbuild',
    name='junit-runner-withretry',
    repo=public,
  ),
  dependencies=[
    '3rdparty:junit',
  ],
  sources=globs('*.java')
)
