# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'context_utils',
  sources = ['context_utils.py'],
  dependencies = [
    'src/python/pants/base:workunit',
    'src/python/pants/build_graph',
    'src/python/pants/goal:context',
    'src/python/pants/goal:run_tracker',
  ],
  tags = {"partially_type_checked"},
)
