python_library(
  name = 'fs',
  sources = globs('*.py'),
  dependencies = [
    pants('src/python/twitter/common/collections'),
    pants('src/python/twitter/common/contextutil'),
    pants('src/python/twitter/common/lang'),
  ]
)
