<?xml version="1.0"?>

<!--
=================================================================================================
Copyright 2011 Twitter, Inc.
_________________________________________________________________________________________________
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this work except in compliance with the License.
You may obtain a copy of the License in the LICENSE file, or at:

 http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=================================================================================================
-->

<!-- generated by pants! -->
<project version="4">
  <component name="CompilerConfiguration">
    <option name="DEFAULT_COMPILER" value="Javac"/>
    <resourceExtensions/>
    <wildcardResourcePatterns>
      % for extension in project.resource_extensions:
      <entry name="?*${extension}"/>
      % endfor
    </wildcardResourcePatterns>
    <annotationProcessing enabled="false" useClasspath="true"/>
  </component>

  <component name="JavacSettings">
    <option name="ADDITIONAL_OPTIONS_STRING" value="-encoding ${project.java_encoding}" />
  </component>

  <component name="ProjectModuleManager">
    <modules>
      % for module in project.modules:
      <module fileurl="file://${module.path}"
              filepath="${module.path}"/>
      % endfor
    </modules>
  </component>

  <component name="ProjectRootManager"
             version="2"
             languageLevel="JDK_1_6"
             project-jdk-name="1.6"
             project-jdk-type="JavaSDK">
    <output url="file://${project.outdir}"/>
  </component>

  <component name="ProjectRunConfigurationManager">
    <configuration default="false" name="Debug on port 5005" type="Remote" factoryName="Remote">
      <option name="USE_SOCKET_TRANSPORT" value="true" />
      <option name="SERVER_MODE" value="false" />
      <option name="SHMEM_ADDRESS" value="javadebug" />
      <option name="HOST" value="localhost" />
      <option name="PORT" value="5005" />
      <method />
    </configuration>
  </component>

  % if project.has_scala:
  <component name="ScalacSettings">
    <option name="USE_FSC" value="${str(project.scala.fsc).lower()}"/>
  </component>
  <component name="libraryTable">
    <library name="scala">
      <CLASSES>
        <root url="jar://${project.root_dir}/build-support/antlib/scala-library-2.8.1.jar!/"/>
        <root url="jar://${project.root_dir}/build-support/antlib/scala-compiler-2.8.1.jar!/"/>
      </CLASSES>
      <JAVADOC />
      <SOURCES />
    </library>
  </component>
  % endif

  <component name="VcsDirectoryMappings">
    <mapping directory="${project.root_dir}" vcs="Git"/>
  </component>

  <%
    checkstyle_suppression_files = ','.join([ project.root_dir + '/build-support/commons/checkstyle/checkstyle_suppressions.xml' ] +
	     [project.root_dir + '/' + relpath for relpath in project.extra_checkstyle_suppression_files ] )
  %>
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration" value="file://${project.root_dir}/build-support/checkstyle/coding_style.xml:Twitter CheckStyle rules." />
        <entry key="check-test-classes" value="test" />
        <entry key="location-0" value="CLASSPATH:/sun_checks.xml:The default CheckStyle rules." />
        <entry key="location-1" value="file://${project.root_dir}/build-support/checkstyle/coding_style.xml:Twitter CheckStyle rules." />
        <entry key="property-1.checkstyle.suppression.files" value="${checkstyle_suppression_files}"/>
        <entry key="thirdparty-classpath" value="${project.root_dir}/build-support/antlib/checkstyle-custom-checks.jar" />
      </map>
    </option>
  </component>

% for component in project.extra_components:
  ${component}

% endfor
</project>
