# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_library(
  dependencies = [
    '3rdparty/python:requests',
    'src/python/pants/subsystem',
    'src/python/pants/util:dirutil',
  ],
)
