# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_library(
  dependencies = [
    'src/python/pants/util:collections_backport',
    '3rdparty/python:requests',
    '3rdparty/python:www-authenticate',
    'src/python/pants/subsystem',
    'src/python/pants/process',
    'src/python/pants/util:dirutil',
    'src/python/pants/util:memo',
  ],
)
