# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'core',
  sources = ['test_wrapped_globs.py'],
  dependencies = [
    pants('src/python/pants/backend/core'),
    pants('tests/python/pants_test:base_test'),
  ]
)
