# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies = [
    'src/python/pants/stats',
    'src/python/pants/util:contextutil',
  ],
)
