# Copyright 2026 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

resources(name="manifest", sources=["images.json"])

python_sources(dependencies=[":manifest"])

python_tests(name="tests")
