# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
  dependencies=[
    '3rdparty:junit',
    'contrib/avro/tests/avro/org/pantsbuild/contrib/avro:simple',
    'contrib/avro/tests/avro/org/pantsbuild/contrib/avro:user',
  ],
)
