# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_grpcio_library(
  sources=['service.proto'],
  dependencies=[
    'examples/3rdparty/python:protobuf',
  ]
)
