# TODO: explain what this whole bootstrapping process means.

python_library(
  name='plugin',
  dependencies=[
    'src/python/pants/goal:task_registrar',
    'src/python/pants/backend/cargo_bootstrap/subsystems',
    'src/python/pants/backend/cargo_bootstrap/targets',
    'src/python/pants/backend/cargo_bootstrap/tasks',
  ],
)
