# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    basename = "wire-element-example",
    main = "org.pantsbuild.example.wire.element.WireElementExample",
    source = "WireElementExample.java",
    dependencies = [
        "3rdparty:wire-runtime",
        "examples/src/wire/org/pantsbuild/example/element",
        "examples/src/wire/org/pantsbuild/example/temperature",
    ],
)
