# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_protobuf_library(name='distance',
  sources=['distances.proto',],
  provides = artifact(
    org = 'com.pants.testproject.protobuf',
    name = 'distance',
    repo = public,
  )
)
