node_module(
  name='server-project',
  sources=globs('package.json', 'src/*.js', 'test/*.js'),
  dependencies=[
    'contrib/node/examples/3rdparty/node/babel',
    'contrib/node/examples/3rdparty/node/mocha',
  ]
)
