# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_binary(
  name = 'lumberjack',
  source = 'lumberjack.py',
  dependencies = [
    'src/python/pants/pantsd/service:fs_event_service',
  ]
)
