# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_test_suite(
  name = 'jvm_compile',
  dependencies = [
    'tests/python/pants_test/tasks/jvm_compile/java',
    'tests/python/pants_test/tasks/jvm_compile/scala',
  ],
)

