python_tests(
  name = 'test_antlr_failure',
  sources = ['donothing.py'],
  dependencies = [
    '3rdparty/python:antlr-3.1.3',
    'testprojects/src/antlr/pants/backend/python/test:antlr_failure',
  ],
)
