services:
  cache:
    image: ${BB_STORAGE_IMAGE}
    command: ["/config/cache.jsonnet"]
    ports:
      - "127.0.0.1::8980"
    volumes:
      - ${BUILDBARN_ASSETS_ROOT}/cache.jsonnet:/config/cache.jsonnet:ro
      - ${BUILDBARN_ASSETS_ROOT}/runtime.libsonnet:/config/runtime.libsonnet:ro
      - ${BUILDBARN_RUNTIME_ROOT}/storage-cas:/storage-cas
      - ${BUILDBARN_RUNTIME_ROOT}/storage-ac:/storage-ac
