# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/engine:addresses',
    'src/python/pants/engine:target',
    'src/python/pants/fs',
    'src/python/pants/util:frozendict',
  ],
  tags = {"type_checked"},
)
