# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

go_protobuf_library(
  name='route-go',
  dependencies=[
    'contrib/go/examples/src/protobuf/org/pantsbuild/example/distance:distance-go',
  ],
)
