# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'distance_directory',
  sources = rglobs('distance/*'),
)

files(
  name = 'import_from_buildroot_directory',
  sources = rglobs('import_from_buildroot/*'),
)

files(
  name = 'proto-ordering_directory',
  sources = rglobs('proto-ordering/*'),
)
