# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    '3rdparty/python:ansicolors',
    'src/python/pants/binaries',
    'src/python/pants/engine:addressable',
    'src/python/pants/engine:native',
    'src/python/pants/engine:parser',
    'src/python/pants/engine:rules',
    'src/python/pants/engine:scheduler',
    'src/python/pants/engine:struct',
    'src/python/pants/util:objects',
    'src/python/pants/testutil/option',
    'src/python/pants/testutil/subsystem',
  ],
)
