# Copyright 2024 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).
python_sources()

python_tests(
    name="tests",
    # dependencies=["pants-plugins/pants.backend.experimental.makeself#pantsbuild.pants"],
)
