# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    '3rdparty/python/twitter/commons:twitter.common.collections',
    'contrib/avro/src/python/pants/contrib/avro/targets',
    'src/python/pants/backend/jvm/targets:java',
    'src/python/pants/backend/jvm/tasks:nailgun_task',
    'src/python/pants/base:exceptions',
    'src/python/pants/build_graph',
    'src/python/pants/java/jar',
    'src/python/pants/option',
    'src/python/pants/task',
    'src/python/pants/util:memo',
  ],
)
