# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

source_root('3rdparty', jar_library)
source_root('src/python', page, python_library, resources)
source_root('tests/python', page, python_library, python_tests, resources)

source_root('examples/src/scalajs', scala_library, scala_js_binary)
