# coding=utf-8
# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    'contrib/confluence/src/python/pants/contrib/confluence/util',
    'src/python/pants/backend/docgen/targets',
    'src/python/pants/base:exceptions',
    'src/python/pants/task',
    'src/python/pants/util:desktop',
    'src/python/pants/util:dirutil',
  ],
  sources=globs('*.py'),
)
