# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='main',
  basename='jaxb-example',
  dependencies=[
    'examples/src/java/com/pants/examples/jaxb/reader',
    'examples/src/resources/com/pants/examples/names',
  ],
  source='ExampleJaxb.java',
  main='com.pants.examples.jaxb.main.ExampleJaxb',
)
