# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

shell_library(sources=["pre-commit", "prepare-commit-msg"], dependencies=["build-support/common.sh"])
