target(
    description = """This target exists at path {}.""".format(buildfile_path()),
    dependencies = [
        "testprojects/src/resources/org/pantsbuild/testproject/ordering:literal",
    ],
)
