# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_antlr_library(
  name = 'eval',
  module = 'pants.python.test',
  sources = ['Eval.g', 'Expr.g'],
)

python_antlr_library(
  name = 'csv',
  module = 'pants.python.test2',
  sources = ['csv.g'],
)
