# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(name = 'greet',
  dependencies = [],
  sources = globs('*.java'),
  provides = artifact(org='org.pantsbuild.testproject.publish',
                      name='hello-greet',
                      repo=testing,),
)
