# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

target(
  name = 'all_directories',
  dependencies = [
    ':test_directory',
  ],
)

files(
  name = 'test_directory',
  sources = ['test/**/*'],
)
