# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
    basename = "wire-roots-example",
    main = "org.pantsbuild.example.wire.roots.WireRootsExample",
    source = "WireRootsExample.java",
    dependencies = [
        "examples/src/wire/org/pantsbuild/example/roots",
    ],
)
