# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    '3rdparty/python:pex',
    'src/python/pants/util:process_handler',
    'src/python/pants/backend/python:interpreter_cache',
    'src/python/pants/backend/python:python_requirement',
    'src/python/pants/backend/python/targets',
    'src/python/pants/backend/python/tasks:python',
    'src/python/pants/base:build_environment',
    'src/python/pants/base:exceptions',
    'src/python/pants/base:workunit',
    'src/python/pants/util:contextutil',
  ],
)
