# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(dependencies=[":scala_sources"])

python_tests(
    name="tests",
)

resources(name="scala_sources", sources=["*.scala"])
