# Copyright 2021 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(dependencies=[":resources"])

python_tests(
    name="tests",
)

resources(name="resources", sources=["*.scala", "*.lock"])
