# ==================================================================================================
# Copyright 2011 Twitter, Inc.
# --------------------------------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this work except in compliance with the License.
# You may obtain a copy of the License in the LICENSE file, or at:
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==================================================================================================

__author__ = 'Brian Wickman'

import os
import sys
import glob
import shutil
import tempfile
import subprocess

from twitter.pants.base import Chroot

class PythonThriftBuilder(object):
  """
    Thrift builder.
  """
  class UnknownPlatformException(Exception):
    def __init__(self, platform):
      Exception.__init__(self, "Unknown platform: %s!" % platform)
  class CodeGenerationException(Exception): pass

  def __init__(self, target, root_dir):
    self.target = target
    self.root = root_dir
    distdir = os.path.join(self.root, 'dist')
    self.chroot = Chroot(root_dir, distdir, target.name)
    codegen_root = tempfile.mkdtemp(dir=self.chroot.path(), prefix='codegen.')
    self.codegen_root = os.path.relpath(codegen_root, self.chroot.path())
    self.detected_packages = set()

  def __del__(self):
    self.cleanup()

  def packages(self):
    return self.detected_packages

  def cleanup(self):
    shutil.rmtree(self.chroot.path())

  @staticmethod
  def thrift_binary(root_dir):
    # TODO(Brian Wickman):  Will we ever need to make this smarter?
    PLATMAP = {
      'darwin': ['mac', '10.6', '0.5.0', 'thrift'],
      'linux': ['linux', 'x86_64', '0.5.0', 'thrift'],
    }
    platform = os.uname()[0].lower()
    if platform not in PLATMAP:
      raise PythonThriftBuilder.UnknownPlatformException(platform)
    return os.path.join(root_dir, 'build-support', 'bin', 'thrift', *PLATMAP[platform])

  def run_thrifts(self):
    for src in self.target.sources:
      if not self._run_thrift(src):
        raise PythonThriftBuilder.CodeGenerationException(
          "Could not generate .py from %s!" % src)

  def _run_thrift(self, source):
    thrift_file = source
    thrift_abs_path = os.path.join(self.root, self.target.target_base, thrift_file)
    thrift_abs_path = os.path.abspath(thrift_abs_path)

    # pushd, call, popd
    cwd = os.getcwd()
    os.chdir(self.chroot.path())
    po = subprocess.Popen([
        PythonThriftBuilder.thrift_binary(self.root),
        '--gen', 'py:new_style',
        '-o', self.codegen_root,
        thrift_abs_path])
    os.chdir(cwd)
    rv = po.wait()
    if rv != 0:
      comm = po.communicate()
      print >> sys.stderr, 'thrift generation failed!'
      print >> sys.stderr, 'STDOUT'
      print >> sys.stderr, comm[0]
      print >> sys.stderr, 'STDERR'
      print >> sys.stderr, comm[1]
    return rv == 0

  @staticmethod
  def path_to_module(path):
    return path.replace(os.path.sep, '.')

  def build_egg(self):
    # autogenerate the python files that we bundle up
    self.run_thrifts()

    genpy_root = os.path.join(self.chroot.path(), self.codegen_root, 'gen-py')
    for dir, subdirs, files in os.walk(os.path.normpath(genpy_root)):
      reldir = os.path.relpath(dir, genpy_root)
      if reldir == '.': continue
      if '__init__.py' not in files: continue
      self.detected_packages.add(self.path_to_module(reldir))

    if not self.detected_packages:
      raise PythonThriftBuilder.CodeGenerationException(
        'No Thrift structures declared in %s!' % self.target)

    def dump_setup_py(packages):
      boilerplate = """
from setuptools import setup

setup(name        = "%(target_name)s",
      version     = "dev",
      description = "autogenerated thrift bindings for %(target_name)s",
      package_dir = { "": "gen-py" },
      packages    = %(packages)s)
"""
      boilerplate = boilerplate % {
        'target_name': self.target.name,
        'genpy_root': genpy_root,
        'packages': repr(list(packages))
      }

      self.chroot.write(boilerplate, os.path.join(self.codegen_root, 'setup.py'))
    dump_setup_py(self.detected_packages)

    egg_path = None

    # TODO(Brian Wickman): Do a sanity check somewhere to ensure that
    # setuptools is on the path?
    cwd = os.getcwd()
    egg_root = os.path.join(self.chroot.path(), self.codegen_root)
    os.chdir(egg_root)
    po = subprocess.Popen([
      sys.executable,
      'setup.py', 'bdist_egg',
      '--dist-dir=dist',
      '--bdist-dir=build.%s' % self.target.name], stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    rv = po.wait()
    if rv == 0:
      eggs = os.path.abspath(os.path.join('dist', '*.egg'))
      eggs = glob.glob(eggs)
      if len(eggs) != 1:
        comm = po.communicate()
        print >> sys.stderr, 'egg generation failed'
        print >> sys.stderr, 'STDOUT'
        print >> sys.stderr, comm[0]
        print >> sys.stderr, 'STDERR'
        print >> sys.stderr, comm[1]
        raise PythonThriftBuilder.CodeGenerationException(
          'Generation of Thrift eggs failed for target = %s' % self.target)
      egg_path = eggs[0]
    os.chdir(cwd)

    return egg_path
