# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    '3rdparty/python:dataclasses',
    '3rdparty/python:libcst',
    'src/python/pants/engine:goal',
    'src/python/pants/engine:rules',
  ],
  tags={'partially_type_checked'},
)
