# coding=utf-8
# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='targets',
  sources=[
    'cpp_binary.py',
    'cpp_library.py',
    'cpp_target.py',
  ],
  dependencies=[
    'src/python/pants:pants-packaged',
  ],
)
