# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'contrib/node/src/python/pants/contrib/node/rules',
    'src/python/pants/engine:target',
  ],
  tags = {"type_checked"},
)
