scala_library(
  provides=scala_artifact(
    org='org.pantsbuild',
    name='zinc-options',
    repo=public,
    publication_metadata=pants_library('The SBT incremental compiler for nailgun')
  ),
  strict_deps=True,
  platform='java8',
)
