# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

scala_library(
    platform = "java8",
    provides = scala_artifact(
        org = "org.pantsbuild",
        name = "zinc-options",
        publication_metadata = pants_library("The SBT incremental compiler for nailgun"),
        repo = public,
    ),
    strict_deps = True,
)
