# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# see test_idea_integration.py
java_library(
  sources = ['Code.java'],
  dependencies=[
      'testprojects/src/resources/org/pantsbuild/testproject/idearesourcesonly:resource',
   ],
)

