# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


target(
  dependencies=[
    'testprojects/maven_layout/junit_resource_collision/onedir/src/test/java:test',
    'testprojects/maven_layout/junit_resource_collision/twodir/src/test/java:test',
  ],
)
