# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(dependencies=[":petstore"])

resources(name="petstore", sources=["petstore_spec.yaml"])
