# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='jvm',
  sources=['test_jvm.py'],
  dependencies = [
    'src/python/pants/backend/jvm/subsystems:jvm',
    'tests/python/pants_test/subsystem:subsystem_utils',
  ],
)
