# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Like Hello world, but built with Pants.

python_library(name='greet',
  dependencies=[
    pants('3rdparty/python:ansicolors'),
  ],
  sources=globs('*.py'),
)
