# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'pants_service',
  sources = ['pants_service.py'],
)

python_library(
  name = 'scheduler_service',
  sources = ['scheduler_service.py'],
)

python_library(
  name = 'store_gc_service',
  sources = ['store_gc_service.py'],
)

python_tests(
  name = 'tests',
)
