# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_grpcio_library(
    name='service',
    sources=['service.proto'],
    dependencies=['3rdparty/python:protobuf',]
)
