# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    'src/python/pants/backend/python/subsystems',
    'src/python/pants/option',
  ],
  tags = {"partially_type_checked"},
)
