# coding=utf-8
# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'distribution',
  sources = globs('distribution/*.py'),
  dependencies = [
    pants('3rdparty/python/twitter/commons:twitter.common.log'),
    ]
)