# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library()

python_tests(
  name='integration',
  sources=['*_integration_test.py'],
  tags=['integration'],
  timeout=330,
)
