# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies=[
    'examples/3rdparty/python:tensorflow',
    'examples/src/python/example/tensorflow_custom_op',
  ],
)
