# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies = [
    'contrib/awslambda/python/src/python/pants/contrib/awslambda/python/subsystems',
    'src/python/pants/backend/python/tasks',
  ]
)
