# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'process',
  sources = globs('*.py'),
  dependencies = [
    pants('3rdparty/python:mox'),
    pants('src/python/pants/process'),
  ]
)
