# Copyright 2016 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='lua_library',
  dependencies=[
    'src/python/pants/build_graph',
  ],
  sources=['lua_library.py']
)
