# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'test_git',
  dependencies = [
    '3rdparty/python:future',
    'src/python/pants/scm',
    'src/python/pants/scm:git',
    'src/python/pants/util:contextutil',
    'src/python/pants/util:dirutil',
    'src/python/pants/util:process_handler',
    'tests/python/pants_test/testutils:git_util',
  ]
)
