# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  dependencies = [
    'src/python/pants/scm',
    'src/python/pants/scm:git',
    'src/python/pants/util:contextutil',
    'src/python/pants/util:dirutil',
    'src/python/pants/testutil:git_util',
  ],
  tags = {"partially_type_checked"},
)
