# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='subsystems',
  sources=globs('*.py'),
  dependencies=[
    'contrib/haskell/src/python/pants/contrib/haskell/subsystems',
    'src/python/pants/util:contextutil',
    'tests/python/pants_test/subsystem:subsystem_utils',
  ]
)
