# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'graph',
  sources = globs('*.py'),
  dependencies = [
    'src/python/pants/base:address',
    'src/python/pants/base:build_file_parser',
    'src/python/pants/base:build_graph',
    'src/python/pants/base:build_root',
    'src/python/pants/base:target',
    'src/python/pants/util:contextutil',
    'src/python/pants/util:dirutil',
  ],
)
