# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name = 'graph',
  sources = ['test_build_graph.py'],
  dependencies = [
    'src/python/pants/base:address',
    'src/python/pants/base:address_lookup_error',
    'src/python/pants/base:build_graph',
    'src/python/pants/base:target',
    'tests/python/pants_test:base_test'
  ],
)
