# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'junit_resource_collision_directory',
  sources = rglobs('junit_resource_collision/*'),
)

files(
  name = 'provided_patching_directory',
  sources = rglobs('provided_patching/*'),
)

files(
  name = 'resource_collision_directory',
  sources = rglobs('resource_collision/*'),
)
