# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='antlr3',
  source='ExampleAntlr3.java',
  main='com.pants.examples.antlr3.ExampleAntlr3',
  dependencies=[
    'examples/src/antlr/com/pants/examples/exp:exp_antlr3',
  ],
)

