# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

pex_binary(name="binary", entry_point="print_env.main", dependencies=[":lib"])

python_sources(name="lib")
