# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_binary(
  entry_point = 'print_env.main',
  sources = ['main.py'],
)
