# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_library(name='missing_sources',
  sources=[],
  dependencies=[':ant'],
)

jar_library(name='ant',
  jars=[
    jar(org='ant', name='ant', rev='1.6.4').with_sources(),
  ],
)
