# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Like Hello world, but built with Pants. This time, with both C++ and Py sources

python_distribution(
  name='superhello2'
)
