page(
  name='readme',
  source='readme.md',
  dependencies=[
    'src/docs:publish',
  ]
)

page(
  name='from_maven',
  source='from_maven.md',
  dependencies=[
    ':3rdparty_jvm',
  ],
)

page(
  name='3rdparty_jvm',
  source='3rdparty_jvm.md',
  dependencies=[
    'src/docs:3rdparty',
  ],
)


