page(
  name='readme',
  source='readme.md',
  dependencies=[
    ':3rdparty_jvm',
    ':from_maven',
    'src/docs:publish',
    'src/docs:first_concepts',
    'src/docs:first_tutorial',
  ]
)

page(
  name='from_maven',
  source='from_maven.md',
  dependencies=[
    ':3rdparty_jvm',
  ],
)

page(
  name='3rdparty_jvm',
  source='3rdparty_jvm.md',
  dependencies=[
    'src/docs:3rdparty',
  ],
)

page(
  name='page',
  source='page.md',
)
