# Copyright 2017 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Like Hello world, but built with a python_distribution.
# python_distribution allows you to use setup.py to depend on C/C++ extensions.

# There must be a single BUILD file and a setup.py in a given python_distribution.

# All you need to indicate is a name and any dependencies.
# You are expected to define source locations in setup.py.
# There should be a one-to-one mapping for the name of the python_distribution
# and the name of the python_distribution's directory. In this case, it's superhello.

python_distribution(
  name='superhello'
)
