# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Like Hello world, but built with Pants. This time, with both C++ and Py sources

# The BUILD file must be in the directory of the Python Distribution, and there must
# only be a single BUILD file in a given directory.

python_distribution(
  name='superhello'
)
