# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_library(
  name = 'plugin',
  sources = ['register.py'],
  dependencies = [
    '3rdparty/python:future',
    'src/python/pants/goal',
    'src/python/pants/goal:task_registrar',
    'src/python/pants/task',
  ]
)

