# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(name='usezip',
  sources=['UseZipTest.java',],
  dependencies=[
    pants('3rdparty:junit'),
    pants('src/protobuf/com/pants/examples/zipped'),
  ],
)