# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='python_setup',
  sources=['test_python_setup.py'],
  dependencies=[
    'src/python/pants/backend/python/subsystems',
    'src/python/pants/util:contextutil',
    'tests/python/pants_test:test_base',
    'tests/python/pants_test/testutils:pexrc_util',
  ]
)
