# coding=utf-8
# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/backend/native/config',
    'src/python/pants/backend/native/subsystems',
    'src/python/pants/backend/native/subsystems/binaries',
    'src/python/pants/backend/native/targets',
    'src/python/pants/backend/native/tasks',
    'src/python/pants/build_graph',
    'src/python/pants/engine:addresses',
    'src/python/pants/engine:target',
    'src/python/pants/goal:task_registrar',
    'src/python/pants/util:collections',
    'src/python/pants/util:frozendict',
  ],
  tags = {"partially_type_checked"},
)
