# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

source_root('src/python', page, python_binary, python_library, resources)
source_root('tests/python', page, python_binary, python_library, python_tests, resources)
source_root('tests/thrift', page, java_thrift_library)
