# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name='scala_tests_directory',
  sources=rglobs('tests/scala/*'),
)

files(
  name='thrift_tests_directory',
  sources=rglobs('tests/thrift/*'),
)
