# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(
  source = 'Manifest.java',
  name = 'manifest',
  main = 'org.pantsbuild.testproject.manifest.Manifest',
  manifest_entries = {
    'Implementation-Version' :  '1.2.3',
  }
)
