# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

java_protobuf_library(
  # These files are intentionally sorted non-alphabetically.
  # A test asserts that source ordering is significant.
  sources=['zestproto3.proto', 'testproto4.proto',],
)
