# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'pants_plugins_directory',
  sources = ['pants-plugins/**/*'],
  dependencies = [
    'src/python/pants/testutil:test_base',
  ],
)
