# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(
  name = 'pants_plugins_directory',
  sources = rglobs('pants-plugins/*'),
  dependencies = [
    'tests/python/pants_test:test_base',
  ],
)
