# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

junit_tests(
  name='runner-tests',
  sources=globs('*.java'),
  dependencies=[
    '3rdparty:junit',
    '3rdparty:guava',
    'src/java/org/pantsbuild/tools/runner:runner-library',
  ],
)
