# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/backend/native/config',
    'src/python/pants/util:osutil',
  ],
  tags = {"partially_type_checked"},
)
