# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name='testutils',
  sources=globs('*.py'),
  dependencies=[
    'src/python/pants/base:target',
    'src/python/pants/reporting',
    'src/python/pants/backend/core/targets:common',
  ],
)
