# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'testutils',
  sources = globs('*.py'),
  dependencies = [
    'src/python/pants/backend/core/targets:common',
    'src/python/pants/build_graph',
    'src/python/pants/reporting',
  ],
)
