# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'mock_logger',
  sources = globs('mock_logger.py'),
  dependencies = [
    'src/python/pants/testutil/utils:mock_logger',
  ],
)

python_library(
  name = 'file_test_util',
  sources = [
    'file_test_util.py',
  ],
  dependencies = [
    'src/python/pants/testutil/utils:file_test_util',
  ],
)

python_library(
  name = 'git_util',
  sources = [
    'git_util.py',
  ],
  dependencies = [
    'src/python/pants/testutil/utils:git_util',
  ],
)

python_library(
  name = 'process_test_util',
  sources = [
    'process_test_util.py',
  ],
  dependencies = [
    'src/python/pants/testutil/utils:process_test_util',
  ],
)

python_library(
  name = 'pexrc_util',
  sources = [
    'pexrc_util.py',
  ],
  dependencies = [
    'src/python/pants/testutil/utils:pexrc_util',
  ],
)
