# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

jvm_binary(name='unpacked_jars',
  basename='protobuf-unpacked-jars-example',
  source='ExampleProtobufExternalArchive.java',
  main='com.pants.examples.protobuf.unpacked_jars.ExampleProtobufExternalArchive',
  dependencies=[
    'examples/src/protobuf/com/pants/examples/unpacked_jars'
  ],
)
