# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

mypy_source_plugin(
  name="total_ordering",
  sources=["total_ordering.py"],
)
