# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    overrides={
        "import_parser.py": {
            "dependencies": ["./scripts/import_parser.py:resources"]
        }
    }
)

python_tests(name="tests")
