name: Scheduled cargo audit
on:
  schedule:
  - cron: 11 8 * * *  # 8:11am
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Cargo audit (for security vulnerabilities)
      run: |
        cargo install cargo-audit --locked
        cd src/rust
        cargo audit
