name: Scheduled cargo audit
on:
  schedule:
  - cron: 11 8 * * *  # 8:11am
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Cargo audit (for security vulnerabilities)
      run: |
        cargo install cargo-audit --locked
        cd src/rust
        cargo audit
