name: Scheduled cargo audit
on:
  schedule:
  - cron: 11 8 * * *  # 8:11am
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Cargo audit (for security vulnerabilities)
      run: |
        cargo install cargo-audit --locked
        cd src/rust
        cargo audit
