name: Scheduled zizmor audit
on:
  schedule:
  - cron: 21 8 * * *  # 8:21am
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  zizmor-audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        sparse-checkout: |
            .
            .github

    - name: Run zizmor
      uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
