name: Scheduled zizmor audit
on:
  schedule:
  - cron: 21 8 * * *  # 8:21am
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  zizmor-audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        sparse-checkout: |
            .
            .github

    - name: Run zizmor
      uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
