name: Create Alpha Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: The alpha release version to create (MAJOR.MINOR.PATCHaN e.g. 2.42.4a0).
        required: true

defaults:
  run:
    shell: bash

jobs:
  org-check:
    name: Check GitHub Organization
    if: ${{ github.repository_owner == 'pantsbuild' }}
    runs-on: ubuntu-latest
    steps:
      - name: Noop
        run: "true"

  github-pr:
    name: Create an alpha release pull request
    needs: org-check
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Determine release version
        id: validate-version
        run: |
          version="${{ inputs.version }}"

          if [[ -z "$version" ]]; then
              echo "::error::An input 'version' must be specified"
              exit 1

          elif (( ${#version} > 10 )); then
              echo "::error::The input 'version' must be smaller than 11 characters (i.e. allows '2.99.99a99')"
              exit 1

          elif [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+a[0-9]+$ ]]; then
              echo "::error::The input version '${version}' must be of the form MAJOR.MINOR.PATCHaN (8.9.10a99)"
              exit 1
          fi

          major_minor=$(echo "$version" | grep -oE '^[0-9]+\.[0-9]+')

          # Use `main` branch for 0a0 (patch 0 + first alpha), otherwise use `MAJOR.MINOR.x` branch
          # TODO: Currently this expects the `MAJOR.MINOR.x` branch to already be created
          # NOTE: This falls over on something like 2.32.10a0 - but, I haven't seen more than 3 patch releases in a while
          if [[ "$version" =~ 0a0$ ]]; then
            base_branch="main"
          else
            base_branch="${major_minor}.x"
          fi

          echo "::notice::Release version is: ${version}, with major-minor: ${major_minor}"
          echo "release-version=${version}" >> $GITHUB_OUTPUT
          echo "major-minor-version=${major_minor}" >> $GITHUB_OUTPUT

          echo "::notice::Base branch is: ${base_branch}"
          echo "base-branch=${base_branch}" >> "$GITHUB_OUTPUT"
      
      - uses: actions/checkout@v6
        with:
          ref: ${{ steps.validate-version.outputs.base-branch }}
          fetch-depth: 0  # Required for contributors file

      - name: Update CONTRIBUTORS.md and VERSION files
        env:
          RELEASE_VERSION: ${{ steps.validate-version.outputs.release-version }}
        run: |
          if [[ -z "$RELEASE_VERSION" ]]; then
              echo "::error::The 'RELEASE_VERSION' was empty"
              exit 1
          fi

          echo "$RELEASE_VERSION" > src/python/pants/VERSION

          # Create an alphabetical list of all contributors, using the .mailmap where available (stripping bots)
          # The `sed` at the end is to match the existing Python code which prefixes a "+ " to each name
          {
            printf "Created as part of the release process.\n\n"
            
            git log --use-mailmap --format=format:%aN HEAD \
              | sort -u \
              | grep -vxF \
                -e "dependabot[bot]" \
                -e "github-actions[bot]" \
                -e "Worker Pants (Pantsbuild GitHub Automation Bot)" \
              | sed 's/^/+ /'
          } > CONTRIBUTORS.md

      - name: Create empty release notes for upcoming version when merging to main
        if: steps.validate-version.outputs.base-branch == 'main'
        env:
          MAJOR_MINOR_VERSION: ${{ steps.validate-version.outputs.major-minor-version }}
          TEMPLATE_PATH: docs/notes/release-notes-template.md
        run: |
          if [[ -z "$MAJOR_MINOR_VERSION" ]]; then
              echo "::error::The 'MAJOR_MINOR_VERSION' was empty"
              exit 1
          fi

          MAJOR=$(echo "$MAJOR_MINOR_VERSION" | grep -oE '^[0-9]+')
          MINOR=$(echo "$MAJOR_MINOR_VERSION" | grep -oE '[0-9]+$')

          if [[ -z "$MAJOR" || -z "$MINOR" ]]; then
              echo "::error::Failed to extract major/minor version components from $MAJOR_MINOR_VERSION"
              exit 1
          fi

          INCREMENTED_MINOR=$((10#${MINOR} + 1))
          NEXT_NOTES_PATH="docs/notes/${MAJOR}.${INCREMENTED_MINOR}.x.md"

          if [[ -f "$NEXT_NOTES_PATH" ]]; then
            echo "::notice::Upcoming release notes already exists at ${NEXT_NOTES_PATH}. Skipping creation..."
          else
            echo "::notice::No release notes found at ${NEXT_NOTES_PATH}. Creating..."
            cp "$TEMPLATE_PATH" "$NEXT_NOTES_PATH"
            sed -i "1s/MAJOR\.MINOR/${MAJOR}.${INCREMENTED_MINOR}/" "$NEXT_NOTES_PATH"
          fi

      - name: Commit changes and create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: ${{ steps.validate-version.outputs.base-branch }}
          RELEASE_VERSION: ${{ steps.validate-version.outputs.release-version }}
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "::error::No changes detected - skipping PR creation"
            exit 1
          fi

          # Assign our general account to the local user
          git config --local user.email "pantsbuild+github-automation@gmail.com"
          git config --local user.name "Worker Pants (Pantsbuild GitHub Automation Bot)"

          # Create and checkout a new release branch
          BRANCH_NAME="automation/release/$RELEASE_VERSION"
          git checkout -b "$BRANCH_NAME"

          # Commit and push to the release branch
          TITLE="Prepare $RELEASE_VERSION"
          git add src/python/pants/VERSION CONTRIBUTORS.md docs/notes/
          git commit -m "$TITLE"
          git push -u origin "$BRANCH_NAME"

          # Create PR from the release branch to main, or stable release branch
          gh pr create \
            --title "$TITLE" \
            --body "" \
            --base "$BASE_BRANCH" \
            --head "$BRANCH_NAME" \
            --label "automation:release-prep,category:internal" \
            --assignee "${{ github.actor }}"
