# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

resources(
  name='fs_test',
  # Note that this test data dir is bundled into a tarfile, to preserve symlink structure
  # when copied into a chroot.
  sources=['fs_test/fs_test.tar'],
)
