# coding=utf-8
# Copyright 2018 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  dependencies=[
    'src/python/pants/task',
    'src/python/pants/backend/cargo_bootstrap/subsystems',
    'src/python/pants/backend/cargo_bootstrap/targets',
  ],
)
