# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


python_tests(
  name = 'wiki_page',
  sources = ['test_wiki_page.py'],
  dependencies = [
    'src/python/pants/backend/docgen/targets',
    'src/python/pants/base:build_environment',
    'src/python/pants/build_graph',
    'tests/python/pants_test:base_test',
  ],
)
