# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).


# EXPERIMENTAL ONLY

pyoxidizer_binary(
    name="pants_oxidized_experimental",
    dependencies=["src/python/pants:pants-packaged"],
    entry_point="pants.bin.pants_loader",
)

