# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'plugin',
  sources = ['register.py'],
  dependencies = [
    'src/python/pants/base:build_environment',
    'src/python/pants/base:build_file_aliases',
  ]
)

