python_library(
  name = 'target_platform',
  sources = [
    'target_platform.py',
  ],
  dependencies = [
    pants('3rdparty/python/twitter/commons:twitter.common.lang'),
    pants('src/python/pants/base:config'),
  ],
)
