python_library(
  name = 'target_platform',
  sources = [
    'target_platform.py',
  ],
  dependencies = [
    '3rdparty/python/twitter/commons:twitter.common.lang',
    'src/python/pants/base:config',
  ],
)
