# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_tests(
  name='build_dictionary_info_extracter',
  sources=['test_build_dictionary_info_extracter.py'],
  coverage=['pants.help.build_dictionary_info_extracter'],
  dependencies=[
    'src/python/pants/build_graph',
    'src/python/pants/help',
  ]
)
