# Copyright 2022 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

files(sources=["dist/**"])
# relocated_files(
#     files_targets=[":dist"],
#     src="src/javascript/explorer/dist",
#     dest="explorer",
# )
