# coding=utf-8
# Copyright 2019 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

from typing import Any, Dict, Iterable, Union, Optional

def ensure_binary(text_or_binary: Union[bytes, str]) -> bytes: ...

def ensure_text(text_or_binary: Union[bytes, str]) -> str: ...

def is_text_or_binary(obj: Any) -> bool: ...

def safe_shlex_split(text_or_binary: Union[bytes, str]) -> str: ...

def shell_quote(s: str) -> str: ...

def safe_shlex_join(arg_list: Iterable[str]) -> str: ...

def create_path_env_var(
    new_entries: Iterable[str],
    env: Optional[Dict[str, str]] = None,
    env_var: str = 'PATH',
    delimiter: str = ':',
    prepend: bool = False
) -> str: ...

def camelcase(string: str) -> str: ...

def pluralize(count: int, item_type: str) -> str: ...

def strip_prefix(string: str, prefix: str) -> str: ...
