# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  sources = ['**/*.py'],
  dependencies = [
    '3rdparty/python:requests',
    'src/python/pants/util:dirutil',
  ],
  tags = {"partially_type_checked"},
)
